#define	UPDATE_SCREEN_ON_CONNECTING1	"經過長時間仍無法連結的話請按ESC鍵"
#define	UPDATE_SCREEN_ON_CONNECTING2	"取消連接，回到最初畫面."          
#define	UPDATE_SCREEN_ON_CONNECTING3	"連結伺服器中. 請稍後..."          


#define	UPDATE_SCREEN_ON_WAIT_INIT_DATA1	"經過長時間仍無法連結的話請按ESC鍵"
#define	UPDATE_SCREEN_ON_WAIT_INIT_DATA2	"取消連接，回到最初畫面."          
#define	UPDATE_SCREEN_ON_WAIT_INIT_DATA3	"連結伺服器中. 請稍後..."          


#define	UPDATE_SCREEN_ON_CONNECTION_LOST	"連結中斷!"

#define	_BDRAW_ON_CREATE_NEW_CHARACTER1	"請輸入角色的名稱."
#define	_BDRAW_ON_CREATE_NEW_CHARACTER2	"請決定角色的性別."
#define	_BDRAW_ON_CREATE_NEW_CHARACTER3	"請選擇角色的膚色."
#define	_BDRAW_ON_CREATE_NEW_CHARACTER4	"屬性剩餘點數: %d 點"
#define	_BDRAW_ON_CREATE_NEW_CHARACTER5	"請在10~14之間輸入你要的數值."

#define MSG_WORLDNAME1	"十字軍伺服器"
#define MSG_WORLDNAME2	"2nd Server"
#define MSG_WORLDNAME3	"3rd Server"
#define MSG_WORLDNAME4	"4th Server"
#define MSG_WORLDNAME5	"5th Server"
#define MSG_WORLDNAME6	"6th Server"
#define MSG_WORLDNAME7	"7th Server"
#define MSG_WORLDNAME8	"8th Server"
#define MSG_WORLDNAME9	"9th Server"
#define MSG_WORLDNAME10	"10th Server"
#define MSG_WORLDNAME11	"11th Server"
#define MSG_WORLDNAME12	"12th Server"
#define MSG_WORLDNAME13	"13th Server"
#define MSG_WORLDNAME14	"14th Server"
#define MSG_WORLDNAME15	"15th Server"
#define MSG_WORLDNAME16	"16th Server"

#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER1	"請輸入角色的名稱."  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER2	"請選擇角色的性別."  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER3	"請選擇角色的膚色."  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER4	"請選擇角色的髮型."  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER5	"請選擇角色的髮色."  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER6	"選擇角色的內衣顏色."

#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER7	"設定人物的力量屬性初始值。"        
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER8	"力量屬性值越大，"                  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER9	"人物的生命值和耐力值就越高，"      
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER10	"並可以裝備更重的武器和"            
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER11	"防具等裝備。"                      
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER12	"設定人物的體值屬性初始值。"        
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER13	"體值屬性越高，"                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER14	"人物的生命值回復速度越快，"        
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER15	"生命值所能擁有的最大值也變的更高，"
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER16	"對物理攻擊的吸收力也會增強。"      
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER17	"設定人物的敏捷屬性初始值。"        
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER18	"敏捷屬性值越高，"                  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER19	"對物理攻擊的迴避率及"              
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER20	"使用武器的命中率均會增強。"        
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER21	"設定人物的智慧屬性初始值。"        
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER22	"智慧屬性值越高，"                  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER23	"可以學習的法術越多，"              
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER24	"法力的最大值也會相對提高。"        
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER25	"設定人物的魔力屬性值。"            
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER26	"魔力屬性值越高，"                  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER27	"施展法術的成功率越高，"            
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER28	"同時魔力的最大值也會更高"          
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER29	"設定人物魅力屬性初始值。"          
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER30	"魅力屬性值到達"                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER31	"一定水準的話， "                   
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER32	"您將能夠組織公會。"                
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER33	" 您還沒設定人物名稱，"             
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER34	"無法創造人物。"                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER35	"請輸入角色的名稱."                 
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER36	"您必須設定所有點數，"              
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER37	"請設定所有剩餘的點數到"            
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER38	"各個屬性上。"                      
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER39	"不能使用特殊字元，"                
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER40	"在你的人物名稱裡面，"              
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER41	"請輸入其他的名稱。"                
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER42	"角色名稱不恰當，"                  
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER43	"請輸入其他名稱。"                  
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER44	"使用上述內容"                      
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER45	"創造遊戲角色，"                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER46	"應特別注意， 當角色創造後，"       
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER47	"不能變更角色的屬性值"              
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER48	"請按角色製作按鍵."                 
                                                                                    
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER49	"回到角色選單."                     
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER50	"設定戰士型屬性值."                 
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER51	"設定魔法師型屬性值."               
#define	UPDATE_SCREEN_ON_CREATE_NEW_CHARACTER52	"設定魔戰士型屬性值."               

#define	UPDATE_SCREEN_ON_LOGIN1	"正在讀取遊戲資料."
#define	UPDATE_SCREEN_ON_LOGIN2	"請稍後."          

#define	ON_KEY_UP1	"尚未設定道具或魔法的快速鍵."               
#define	ON_KEY_UP2	"若要設定快速鍵[F2]在裝備道具或施展魔法後，"
#define	ON_KEY_UP3	"按下[Control]＋[F2]鍵即可設定."            

#define	ON_KEY_UP4	"道具(%s %s %s): 設定了[F2]按鍵."
#define	ON_KEY_UP5	"魔法(%s): 設定了[F2]按鍵."      

#define	ON_KEY_UP6	" 快速鍵無適當的道具或魔法."                 
#define	ON_KEY_UP7	" 若要設定快速鍵[F2]在裝備道具或施展魔法後，"
#define	ON_KEY_UP8	" 按下[Control]+[F2]鍵即可設定."             

#define	ON_KEY_UP9	"為了施用魔法應空出雙手."
#define	ON_KEY_UP10	"技能使用中無法施放魔法."
#define	CANT_CAST_MAGIC_ON_PEACE_MODE	"在和平模式中無法使用魔法."

#define	ON_KEY_UP12	"尚未設定符合快速鍵的道具或魔法."         
#define	ON_KEY_UP13	"若要設定快速鍵[F3]在裝備道具或施展魔法後"
#define	ON_KEY_UP14	" 按下[Control]+[F3]鍵即可設定."          

#define	ON_KEY_UP15	"道具(%s %s %s): 由[F3]按鍵設定."
#define	ON_KEY_UP16     "魔法(%s): 由[F3]按鍵設定."      

#define	ON_KEY_UP17	"快速鍵無適當的道具或魔法."                              
#define	ON_KEY_UP18	"若要設定快速鍵[F3]在裝備道具或施展魔法後"               
#define	ON_KEY_UP19	"[Control]-按下[F3]鍵即可設定."                          
                                                                                 
#define	ON_KEY_UP26	"無設定的特殊能力."                                      
#define	ON_KEY_UP28	"使用特殊能力."                                          
                                                                                 
#define	ON_KEY_UP29	"減少敵人生命值50%%的特殊能力: 約在%d分後可使用."        
#define	ON_KEY_UP30	"凍結敵人的特殊能力: 約在%d分後可使用."                  
#define	ON_KEY_UP31	"麻痺敵人的特殊能力: 約在%d分後可使用."                  
#define	ON_KEY_UP32	"同時殺敵的特殊能力: 約在%d分後可使用."                  
#define	ON_KEY_UP33	"吸取敵人生命值的特殊能力: 約在%d分後可使用."            
#define	ON_KEY_UP34	"破壞敵人武器的特殊能力: 約在%d分後可使用."              
#define	ON_KEY_UP35	"防護物理攻擊的特殊能力: 約在%d分後可使用."              
#define	ON_KEY_UP36	"在一定時間內，玩家不被攻擊的特殊能力: 約在%d分後可使用."
                                                                                 
#define	ON_KEY_UP37	"減少敵人生命值50%%的特殊能力: 約在%d秒後可使用."        
#define	ON_KEY_UP38	"凍結敵人的特殊能力: 約在%d秒後可使用."                  
#define	ON_KEY_UP39	"麻痺敵人的特殊能力: 約在%d秒後可使用."                  
#define	ON_KEY_UP40	"同時殺敵的特殊能力: 約在%d秒後可使用."                  
#define	ON_KEY_UP41	"吸取敵人生命值的特殊能力: 約在%d秒後可使用."            
#define	ON_KEY_UP42	"破壞敵人武器的特殊能力: 約在%d秒後可使用."              
#define	ON_KEY_UP43	"防護物理攻擊的特殊能力: 約在%d秒後可使用."              
#define	ON_KEY_UP44	"在一定時間內，玩家不被攻擊的特殊能力: 約在%d秒後可使用."


#define	UPDATE_SCREEN_ON_QUERY_FORCE_LOGIN1	"你的帳號正在連結中，"         
#define	UPDATE_SCREEN_ON_QUERY_FORCE_LOGIN2	"要強制中斷現在的連結嗎?"      
#define	UPDATE_SCREEN_ON_QUERY_FORCE_LOGIN3	"     "                        
                                                                               
	                                                                       
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER1	"使用選擇的角色連結遊戲."      
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER2	"選擇欲連結的角色後"           
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER3	"按下Enter鍵或使用游標選取"    
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER4	"即可連結."                    
                                                                               
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER5	"製作新角色."                  
                                                                               
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER6	"清除選擇的角色. 清除的角色"   
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER7	"無法再恢復, 50級以上的角色"   
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER8	"無法使用此方式清除."          
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER9	"欲刪除50級以上的角色請將 "    
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER10	"帳號名稱及角色名稱,身分證影本"
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER11	"以傳真的方式通知管理者."      
                                                                               
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER12	"變更密碼 ."                   
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER13	"回到原始選單."                

#define	UPDATE_SCREEN_ON_SELECT_CHARACTER14	"沒有角色在此遊戲帳號中."          
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER15	"一個帳號最多可擁有4個角色"        
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER16	"點選左側捲軸的空格或者"           
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER17	"按下上端的創造新角色按鍵"         
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER18	"以創造新角色."                    
                                                                                   
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER19	"選擇要進行遊戲的角色後"           
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER20	"按下開始鍵開始遊戲或者"           
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER21	"創造新角色. 若要刪除已存在的"     
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER22	"角色在選擇角色後"                 
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER23	"按下刪除角色鍵即可"               
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER24	"選擇你要刪除遊戲的角色"           
                                                                                   
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER25	"選擇要進行遊戲的角色後"           
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER26	"按下開始鍵開始進行遊戲或者"       
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER27	"可按下刪除角色鍵"                 
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER28	"刪除所選取的角色."                
                                                                                   
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER31	"帳號未正式登錄."                  
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER34	"未正式登錄的 IP."                 
#define	UPDATE_SCREEN_ON_SELECT_CHARACTER36	"測試伺服器 : Test Server"         
                                                                                   
#define	UPDATE_SCREEN_ON_WATING_RESPONSE1	"經過長時間仍無法連結的話請按ESC鍵"
#define	UPDATE_SCREEN_ON_WATING_RESPONSE2	"取消連接回到最初畫面."            
#define	UPDATE_SCREEN_ON_WATING_RESPONSE3	"連結伺服器中. 請稍候..."          

#define	UPDATE_SCREEN_ON_QUERY_DELETE_CHARACTER1	"角色名稱"         
#define	UPDATE_SCREEN_ON_QUERY_DELETE_CHARACTER2	"要刪除以上角色嗎?"

#define	NOTIFY_MSG_HANDLER1	"%s 已參加你的隊伍."                                         
#define	NOTIFY_MSG_HANDLER2	"%s 已經離開你的隊伍."                                       
#define NOTIFY_MSG_HANDLER3     "%d秒之內無法移動到%s以外的其他區域."                        
                                                                                             
#define	NOTIFY_MSG_HANDLER4	"使用特殊能力!"                                              
#define	NOTIFY_MSG_HANDLER5	"減少敵人生命值50%%的特殊能力: 已發動！約可使用%d秒."        
#define	NOTIFY_MSG_HANDLER6	"凍結敵人的特殊能力: 已發動！約可使用%d秒."                  
#define	NOTIFY_MSG_HANDLER7	"麻痺敵人的特殊能力: 已發動！約可使用%d秒."                  
#define	NOTIFY_MSG_HANDLER8	"同時殺敵的特殊能力: 已發動！約可使用%d秒."                  
#define	NOTIFY_MSG_HANDLER9	"吸取敵人生命值的特殊能力: 已發動！約可使用%d秒."            
#define	NOTIFY_MSG_HANDLER10	"破壞敵人武器的特殊能力: 已發動！約可使用%d秒."              
#define	NOTIFY_MSG_HANDLER11	"防護物理攻擊的特殊能力: 已發動！約可使用%d秒."              
#define	NOTIFY_MSG_HANDLER12	"在一定時間內，玩家不被攻擊的特殊能力: 已發動！約可使用%d秒."
                                                                                             
#define	NOTIFY_MSG_HANDLER13	"特殊能力已被設定！"                                         
#define	NOTIFY_MSG_HANDLER14	"減少敵人生命值50%%的特殊能力: 約在%d分後可使用."            
#define	NOTIFY_MSG_HANDLER15	"凍結敵人的特殊能力: 約在%d分後可使用."                      
#define	NOTIFY_MSG_HANDLER16	"麻痺敵人的特殊能力: 約在%d分後可使用."                      
#define	NOTIFY_MSG_HANDLER17	"同時殺敵的特殊能力: 約在%d分後可使用."                      
#define	NOTIFY_MSG_HANDLER18	"吸取敵人生命值的特殊能力: 約在%d分後可使用."                
#define	NOTIFY_MSG_HANDLER19	"破壞敵人武器的特殊能力: 約在%d分後可使用."                  
#define	NOTIFY_MSG_HANDLER20	"防護物理攻擊的特殊能力: 約在%d分後可使用."                  
#define	NOTIFY_MSG_HANDLER21	"在一定時間內，玩家不被攻擊的特殊能力: 約在%d分後可使用."    
                                                                                             
#define	NOTIFY_MSG_HANDLER22	"減少敵人生命值50%%的特殊能力: 約在%d秒後可使用."            
#define	NOTIFY_MSG_HANDLER23	"凍結敵人的特殊能力: 約在%d秒後可使用."                      
#define	NOTIFY_MSG_HANDLER24	"麻痺敵人的特殊能力: 約在%d秒後可使用."                      
#define	NOTIFY_MSG_HANDLER25	"同時殺敵的特殊能力: 約在%d秒後可使用."                      
#define	NOTIFY_MSG_HANDLER26	"吸取敵人生命值的特殊能力: 約在%d秒後可使用."                
#define	NOTIFY_MSG_HANDLER27	"破壞敵人武器的特殊能力: 約在%d秒後可使用."                  
#define	NOTIFY_MSG_HANDLER28	"防護物理攻擊的特殊能力: 約在%d秒後可使用."                  
#define	NOTIFY_MSG_HANDLER29	"在一定時間內，玩家不被攻擊的特殊能力: 約在%d秒後可使用."    
                                                                                             
#define	NOTIFY_MSG_HANDLER30	"特殊能力使用時間終了！20分鐘後才可使用"                     
#define	NOTIFY_MSG_HANDLER31	"解除特殊能力限制設定！"                                     
#define	NOTIFY_MSG_HANDLER32	"現在可以使用特殊能力了！"                                   
                                                                                             
#define	NOTIFY_MSG_HANDLER33	"你把能源球誤送入敵人的能源傳送門!你的貢獻度下降10..."       
#define	NOTIFY_MSG_HANDLER34	"阿瑞登所屬 %s: 將能源球丟棄在敵國的 能源傳送門..."          
#define	NOTIFY_MSG_HANDLER34_ELV "愛芬所屬 %s: 將能源球丟棄在敵國的能源傳送門..."
#define	NOTIFY_MSG_HANDLER35	"恭喜! 將能源球用能源傳送門帶來可得到經驗值和貢獻度5點!"           
#define	NOTIFY_MSG_HANDLER36	"愛芬所屬 %s :將能源球放入愛芬國的能源傳送門!"                     
#define	NOTIFY_MSG_HANDLER37	"阿瑞登所屬 %s : 將能源球放入阿瑞登的能源傳送門!"                  
#define	NOTIFY_MSG_HANDLER38	"能源球在交戰國界座標(%d, %d)產生!"                                
#define	NOTIFY_MSG_HANDLER39	"將能源球放入所屬國家的能源傳送門內,玩家可得到許多經驗值及貢獻度." 
#define	NOTIFY_MSG_HANDLER40	"觀察者模式開啟. 按下'SHIFT + ESC' 登出..."                        
#define	NOTIFY_MSG_HANDLER41	"觀察者模式關閉"                                                   
#define	NOTIFY_MSG_HANDLER42	"道具製作成功!"                                                    
#define	NOTIFY_MSG_HANDLER43	"道具製作失敗."                                                    
#define	NOTIFY_MSG_HANDLER44	"恭喜! 你的任務完成!"                                              
#define	NOTIFY_MSG_HANDLER45	"無法在指定的位置安插旗幟!"                                        
#define	NOTIFY_MSG_HANDLER46	"藥劑製造成功!"                                                    
#define	NOTIFY_MSG_HANDLER47	"藥劑製造失敗!"                                                    
#define	NOTIFY_MSG_HANDLER48	"鍊金術的技能太低無法製作藥劑."                                    
#define	NOTIFY_MSG_HANDLER49	"現有材料無法組合成藥劑."                                          
#define	NOTIFY_MSG_HANDLER50	"安全攻擊模式啟動."                                                
#define	NOTIFY_MSG_HANDLER51	"安全攻擊模式解除."                                                
#define	NOTIFY_MSG_HANDLER52	"移動或被其他玩家妨礙以至於無法釣魚!"                              
#define	NOTIFY_MSG_HANDLER53	"其他玩家已經將魚釣完了! 好可惜喔..."                              
#define	NOTIFY_MSG_HANDLER54	"沒有魚無法再釣魚!"                                                
#define	NOTIFY_MSG_HANDLER55	"釣魚成功!!!"                                                      
#define	NOTIFY_MSG_HANDLER56	"釣魚失敗!!!"                                                      
#define	NOTIFY_MSG_HANDLER58	"你無法使用管理者命令."                                            
#define	NOTIFY_MSG_HANDLER59	"你無權限使用公會會長命令."                                        
#define	NOTIFY_MSG_HANDLER60	"你成功地將公會成員由公會中驅逐."                                  
#define	NOTIFY_MSG_HANDLER61	"不是你的公會成員."                                                
#define	NOTIFY_MSG_HANDLER62	"停留的時間到了，你將被召回."                                      
#define	NOTIFY_MSG_HANDLER63	"無法再保管道具."                                                  
#define	NOTIFY_MSG_HANDLER64	"等級19以上無法設定為旅行家. 請到市政大廳取得市民權."              
#define	NOTIFY_MSG_HANDLER65	"無法再擁有道具."                                                  
#define	NOTIFY_MSG_HANDLER66	"沒有存放道具的空間或超過重量限制."                                
#define	NOTIFY_MSG_HANDLER67	"金幣不夠."                                                        
#define	NOTIFY_MSG_HANDLER68	"已取消競技場強制召喚模式."                                        
#define	NOTIFY_MSG_HANDLER69	"已設定競技場強制召喚模式."                                        
#define	NOTIFY_MSG_HANDLER70	"遊戲管理員取消了競技場之預約."                                    
#define	NOTIFY_MSG_HANDLER71	"超過競技場預約時間取消競技場預約."                                
#define	NOTIFY_MSG_HANDLER72	"已全部得到入場券."                                                
#define	NOTIFY_MSG_HANDLER73    " %d號競技場預約成功."


#define	RESERVE_FIGHTZONE_RESPONSE_HANDLER1	"競技場預約進行中!"
#define	RESERVE_FIGHTZONE_RESPONSE_HANDLER2	"競技場預約失敗."


#define	UPDATE_SCREEN_ON_LOG_MSG1	"帳號"                          
#define	UPDATE_SCREEN_ON_LOG_MSG2	"密碼"                          
#define	UPDATE_SCREEN_ON_LOG_MSG3	"新密碼"                        
#define	UPDATE_SCREEN_ON_LOG_MSG4	"密碼確認"                      
#define	UPDATE_SCREEN_ON_LOG_MSG5	"密碼不正確."                   
#define	UPDATE_SCREEN_ON_LOG_MSG6	"這個帳號不存在."               
#define	UPDATE_SCREEN_ON_LOG_MSG7	"請確認帳號名稱."               
#define	UPDATE_SCREEN_ON_LOG_MSG8	"遊戲伺服器沒有回應"            
#define	UPDATE_SCREEN_ON_LOG_MSG9	"無法連結的狀態."               
#define	UPDATE_SCREEN_ON_LOG_MSG10	"請稍候再試."                   
#define	UPDATE_SCREEN_ON_LOG_MSG11	"已製作新帳號."                 
#define	UPDATE_SCREEN_ON_LOG_MSG12	"無法使用新帳號登入."           
#define	UPDATE_SCREEN_ON_LOG_MSG13	"無法建立帳號."                 
#define	UPDATE_SCREEN_ON_LOG_MSG14	"帳號名稱已存在."               
#define	UPDATE_SCREEN_ON_LOG_MSG15	"請輸入其他帳號名稱."           
#define	UPDATE_SCREEN_ON_LOG_MSG16	"已製作新角色."                 
#define	UPDATE_SCREEN_ON_LOG_MSG17	"無法製作新角色."               
#define	UPDATE_SCREEN_ON_LOG_MSG18	"帳號名稱已存在."               
#define	UPDATE_SCREEN_ON_LOG_MSG19	"請輸入其他角色名稱."           
#define	UPDATE_SCREEN_ON_LOG_MSG20	"角色已成功地刪除."             
#define	UPDATE_SCREEN_ON_LOG_MSG21	"密碼已成功地變更."             
#define	UPDATE_SCREEN_ON_LOG_MSG22	"無法變更密碼."                 
                                                                        
#define	UPDATE_SCREEN_ON_LOG_MSG23	"角色資料異常無法連結"          
#define	UPDATE_SCREEN_ON_LOG_MSG24	"請洽詢遊戲管理者."             
                                                                        
#define	UPDATE_SCREEN_ON_LOG_MSG25	"測試版的角色無法連線"          
#define	UPDATE_SCREEN_ON_LOG_MSG26	"角色無法連結. 需要由登錄的IP"  
#define	UPDATE_SCREEN_ON_LOG_MSG27	"連結或者登錄個人資料."         
                                                                        
#define	UPDATE_SCREEN_ON_LOG_MSG28	"符合現在登錄的IP住址超過"      
#define	UPDATE_SCREEN_ON_LOG_MSG29	"最多使用人數無法連結."         
                                                                        
#define	UPDATE_SCREEN_ON_LOG_MSG30	"現在遊戲伺服器關閉無法進行連結"
#define	UPDATE_SCREEN_ON_LOG_MSG31	"請稍候再重新連結."             
                                                                        
#define	UPDATE_SCREEN_ON_LOG_MSG32	"您的帳號被鎖定!"               
#define	UPDATE_SCREEN_ON_LOG_MSG33	"請稍候再重新連結."             
#define	UPDATE_SCREEN_ON_LOG_MSG34	"帳號被鎖定無法連結."           
#define	UPDATE_SCREEN_ON_LOG_MSG35	"鎖定時間: %d年 %d月 %d日 為止" 
                                                                        
#define	UPDATE_SCREEN_ON_LOG_MSG38	"要求中斷現在帳號的連結."       
#define	UPDATE_SCREEN_ON_LOG_MSG39	"請稍候再重新連結."             
#define	UPDATE_SCREEN_ON_LOG_MSG40	"現在world伺服器沒有回應."      
#define	UPDATE_SCREEN_ON_LOG_MSG41	"請稍候再重新連結."             
#define	UPDATE_SCREEN_ON_LOG_MSG42	"超過伺服器的最多使用者限制."   

#define	RETIEVE_ITEM_HANDLER4	"領回保管中的%s."

#define	ERASE_ITEM	"道具(%s %s %s): 由[F%d]快速鍵解除.."
#define	ERASE_ITEM1	"道具(%s %s %s): 由[F2]快速鍵解除.."
#define	ERASE_ITEM2	"道具(%s %s %s): 由[F3]快速鍵解除."


#define	BDLBBOX_DOUBLE_CLICK_INVENTORY1	"現在的道具使用結束後才能使用."                       
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY2 "   "	                                              
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY3	"道具 %s: 在生命值減少的10秒內，無法使用捲軸類的道具."
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY4	"為了使用此道具應空出雙手."                           
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY5	"正在使用其他技能."                                   
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY6	"無法使用已損毀的道具."                               
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY7	"道具 (%s):請選擇欲使用的位置."                       
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY8	"道具 (%s): 選擇要使用的對象."                        
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY9	"為了使用此道具應學習鍊金術."                         
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY10	"使用鍊金術..."                                              
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY11	"為了使用此道具應學習武器-防具製作技能."                     
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY12	"使用武器-防具製作技能..."                                   
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY13	"使用技能時無法使用."                                        
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY14	"要製作物品的話，必須要有武器防具製作用車床，請在打鐵屋購買."
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY15	"要用鍊金術的話，必須要有鍊金釜，請至道具店購買 "             
#define	BDLBBOX_DOUBLE_CLICK_INVENTORY16	"要用鍊金術的話必須要去學習.請至道具店購買鍊金術手冊 ."      
                                                                                                             
                                                                                                             
#define	UPDATE_SCREEN_ON_CHANGE_PASSWORD1	"帳號"                                                       
#define	UPDATE_SCREEN_ON_CHANGE_PASSWORD2	"密碼"                                                       
#define	UPDATE_SCREEN_ON_CHANGE_PASSWORD3	"新密碼"                                                     
#define	UPDATE_SCREEN_ON_CHANGE_PASSWORD4	"密碼確認"                                                   
#define	UPDATE_SCREEN_ON_CHANGE_PASSWORD5	"請輸入欲變更的帳號名稱及密碼"                               
#define	UPDATE_SCREEN_ON_CHANGE_PASSWORD6	"新密碼需區分大小文字"                                       
#define	UPDATE_SCREEN_ON_CHANGE_PASSWORD7	"並輸入8個字以上."                                           


#define	DLGBOX_CLICK_SYSMENU1	"遊戲重新開始...%d"        
#define	DLGBOX_CLICK_SYSMENU2	"登出遊戲的時間倒數己終止."


#define	NPC_NAME_SLIME	"史萊姆"
#define	NPC_NAME_SKELETON	"骷髏人"
#define	NPC_NAME_STONEGOLEM	"石巨人"
#define	NPC_NAME_CYCLOPS	"獨眼巨人"
#define	NPC_NAME_ORC	"半獸人"
#define	NPC_NAME_SHOP_KEEPER	"道具店老闆"
#define	NPC_NAME_GIANTANT	"巨大螞蟻"
#define	NPC_NAME_GIANTSCORPION	"毒蠍"
#define	NPC_NAME_ZOMBIE	"殭屍"
#define	NPC_NAME_MAGICIAN	"魔法師"
#define	NPC_NAME_WAREHOUSE_KEEPER	"倉庫主人"
#define	NPC_NAME_GUARD	"警衛"
#define	NPC_NAME_SNAKE	"蛇"
#define	NPC_NAME_CLAYGOLEM	"泥巨人"
#define	NPC_NAME_BLACKSMITH_KEEPER	"鐵匠"
#define	NPC_NAME_CITYHALL_OFFICER	"市政大廳管理員"
#define	NPC_NAME_GUILDHALL_OFFICER	"公會大廳管理員"
#define	NPC_NAME_HELHOUND	"地獄犬"
#define	NPC_NAME_TROLL	"山洞巨人"
#define	NPC_NAME_OGRE	"食人魔"
#define	NPC_NAME_LICHE	"死靈法師"
#define	NPC_NAME_DEMON	"魔鬼"
#define	NPC_NAME_UNICORN	"獨角獸"
#define	NPC_NAME_WEREWOLF	"狼人"
#define	NPC_NAME_DUMMY	"木頭人"
#define NPC_NAME_RABBIT	"兔子"
#define NPC_NAME_CAT	"貓"
#define NPC_NAME_FROG	"蟾蜍"

#define NPC_NAME_MOUNTAIN_GIANT	"野蠻人"
#define NPC_NAME_ETTIN	        "雙頭巨人"
#define NPC_NAME_CANNIBAL	     "食人花"
#define NPC_NAME_RUDOLPH		"麋鹿"
#define NPC_NAME_DIREBOAR		"紅毛豬"
#define NPC_NAME_FROST			"冰雪妖精"
#define NPC_NAME_ICEGOLEM		"冰石巨人"
#define NPC_NAME_WYVERN			"雪龍"

#define NPC_NAME_MCGAFFIN		"村民"
#define NPC_NAME_PERRY			"村女"
#define NPC_NAME_DEVLIN			"魔法師"

#define NPC_NAME_WATERMELON		"西瓜"
#define NPC_NAME_PUMPKIN		"南瓜"
#define NPC_NAME_GARLIC			"大蒜"
#define NPC_NAME_BARLEY			"大麥"
#define NPC_NAME_CARROT			"紅蘿蔔"
#define NPC_NAME_RADISH			"白蘿蔔"
#define NPC_NAME_CORN			"玉蜀黍"
#define NPC_NAME_CHINESEBELLFLOWER	"桔梗花"
#define NPC_NAME_MELONE			"哈密瓜"
#define NPC_NAME_TOMMATO		"番茄"
#define NPC_NAME_GRAPES			"葡萄"
#define NPC_NAME_BLUEGRAPES		"青葡萄"
#define NPC_NAME_MUSHROOM		"香菇"
#define NPC_NAME_GINSENG		"人參"
#define NPC_NAME_CROP			"農作物"

#define	NPC_NAME_ENERGYSPHERE	"能源球"            
#define	NPC_NAME_ARROWGUARDTOWER_CK	"箭矢守護台元件"    
#define	NPC_NAME_ARROWGUARDTOWER	"箭矢守護台"        
#define	NPC_NAME_CANNONGUARDTOWER_CK	"巨炮守護台元件"    
#define	NPC_NAME_CANNONGUARDTOWER	"巨炮守護台"        
#define	NPC_NAME_MANACOLLECTOR_CK	"魔法能量採集機元件"
#define	NPC_NAME_MANACOLLECTOR	"魔法能量採集機"    
#define	NPC_NAME_DETECTOR_CK	"偵測儀元件"        
#define	NPC_NAME_DETECTOR	"偵測儀"            
#define	NPC_NAME_ENERGYSHIELD	"能源防護裝置"      
#define	NPC_NAME_GRANDMAGICGENERATOR	"高級魔法發動機"    
#define	NPC_NAME_MANASTONE	"魔法石"            
#define	NPC_NAME_LIGHTWARBEETLE	"輕戰鬥甲蟲"        
#define	NPC_NAME_GODSHANDKNIGHT	"神之劍 "           
#define	NPC_NAME_GODSHANDKNIGHT_CK	"神之劍騎兵 "       
#define	NPC_NAME_TEMPLEKNIGHT	"教壇之刀 "         
#define	NPC_NAME_BATTLEGOLEM	"戰鬥泥人 "         
#define	NPC_NAME_STALKER	"史塔克"            
#define	NPC_NAME_HELLCLAW	"地獄爪"            
#define	NPC_NAME_TIGERWORM	"虎紋蟲"            
#define	NPC_NAME_CATAPULT	"投石器"            
#define	NPC_NAME_GARGOYLE	"魔武士"           
#define	NPC_NAME_BEHOLDER	"多眼怪"           
#define	NPC_NAME_DARKELF	"黑暗精靈"         

#define	DRAW_OBJECT_NAME50	"狂暴"             
#define	DRAW_OBJECT_NAME51	"凍結"             
#define	DRAW_OBJECT_NAME52	"千里眼"           
#define	DRAW_OBJECT_NAME53	"魔法保護失效"     
#define	DRAW_OBJECT_NAME54	"反物理傷害"       
#define	DRAW_OBJECT_NAME55	"反魔法傷害"       
#define	DRAW_OBJECT_NAME56	"中毒的"           
#define	DRAW_OBJECT_NAME57	"巨毒"             
#define	DRAW_OBJECT_NAME58	"爆炸"             
#define	DRAW_OBJECT_NAME59	"大爆炸"           
#define	DRAW_OBJECT_NAME60	"旅行家"           
#define	DRAW_OBJECT_NAME61	"旅行家,"          
#define	DRAW_OBJECT_NAME62	"阿瑞登"           
#define	DRAW_OBJECT_NAME63	"阿瑞登國民,"      
#define	DRAW_OBJECT_NAME64	"阿瑞登"           
#define	DRAW_OBJECT_NAME65	"阿瑞登所屬犯罪者,"
#define	DRAW_OBJECT_NAME66	"公會成員,"        
#define	DRAW_OBJECT_NAME67	"阿瑞登公會成員"   
#define	DRAW_OBJECT_NAME68	"阿瑞登公會成員,"  
#define	DRAW_OBJECT_NAME69	"公會會長,"        
#define	DRAW_OBJECT_NAME70	"阿瑞登公會會長"   
#define	DRAW_OBJECT_NAME71	"阿瑞登公會成員"   
#define	DRAW_OBJECT_NAME72	"阿瑞登公會會長"   
#define	DRAW_OBJECT_NAME73	"阿瑞登公會會長,"  
#define	DRAW_OBJECT_NAME74	"愛芬所屬"         
#define	DRAW_OBJECT_NAME75	"愛芬國民,"        
#define	DRAW_OBJECT_NAME76	"愛芬所屬"         
#define	DRAW_OBJECT_NAME77	"愛芬所屬犯罪者,"  
#define	DRAW_OBJECT_NAME78	"公會成員,"        
#define	DRAW_OBJECT_NAME79	"愛芬公會成員"     
#define	DRAW_OBJECT_NAME80	"愛芬公會成員,"    
#define	DRAW_OBJECT_NAME81	"公會會長,"        
#define	DRAW_OBJECT_NAME82	"愛芬公會會長"     
#define	DRAW_OBJECT_NAME83	"愛芬公會成員"     
#define	DRAW_OBJECT_NAME84	"愛芬公會會長"     
#define	DRAW_OBJECT_NAME85	"愛芬公會會長,"    
#define	DRAW_OBJECT_NAME86	"犯罪者,"          
#define	DRAW_OBJECT_NAME87	"未知"             
#define	DRAW_OBJECT_NAME88	"中立"             
#define	DRAW_OBJECT_NAME89	"(我方)"           
#define	DRAW_OBJECT_NAME90	"(敵人)"           
#define	DRAW_OBJECT_NAME91	"(威脅)"           

#define	UPDATE_SCREEN_ON_VERSION_NO_MATCH1	"版本不一致!"                  
#define	UPDATE_SCREEN_ON_VERSION_NO_MATCH2	"請下載最新版的遊戲程式後連結."


#define	DRAW_VERSION1	"啟用管理者監視機能的版本 ."     
                                                         
                                                         
#define	USE_RED_POTION1	"使用完其他道具後才可使用此道具."
#define	USE_RED_POTION2	"在交換過程中，不能使用藥劑."    


#define	USE_BLUE_POTION1	"使用完其他道具後才可使用此道具."
#define	USE_BLUE_POTION2	"在交換過程中，不能使用藥劑."    


#define	GET_OFFICIAL_MAP_NAME1	"阿瑞登農場"           
#define	GET_OFFICIAL_MAP_NAME2	"愛芬農場"             
#define	GET_OFFICIAL_MAP_NAME3	"新手村"               
#define	GET_OFFICIAL_MAP_NAME4	"阿瑞登訓練場地下1樓"  
#define	GET_OFFICIAL_MAP_NAME5	"阿瑞登訓練場地下1樓"  
#define	GET_OFFICIAL_MAP_NAME6	"阿瑞登訓練場地下2樓"  
#define	GET_OFFICIAL_MAP_NAME7	"阿瑞登訓練場地下2樓"  
#define	GET_OFFICIAL_MAP_NAME8	"愛芬訓練場地下1樓"    
#define	GET_OFFICIAL_MAP_NAME9	"愛芬訓練場地下1樓"    
#define	GET_OFFICIAL_MAP_NAME10	"愛芬訓練場地下2樓"    
#define	GET_OFFICIAL_MAP_NAME11	"愛芬訓練場地下2樓"    
#define	GET_OFFICIAL_MAP_NAME12	"1號競技場"            
#define	GET_OFFICIAL_MAP_NAME13	"2號競技場"            
#define	GET_OFFICIAL_MAP_NAME14	"3號競技場"            
#define	GET_OFFICIAL_MAP_NAME15	"4號競技場"            
#define	GET_OFFICIAL_MAP_NAME16	"5號競技場"            
#define	GET_OFFICIAL_MAP_NAME17	"6號競技場"            
#define	GET_OFFICIAL_MAP_NAME18	"7號競技場"            
#define	GET_OFFICIAL_MAP_NAME19	"8號競技場"            
#define	GET_OFFICIAL_MAP_NAME20	"9號競技場"            
#define	GET_OFFICIAL_MAP_NAME21	"阿瑞登地城地下1樓"    
#define	GET_OFFICIAL_MAP_NAME22	"阿瑞登"               
#define	GET_OFFICIAL_MAP_NAME23	"愛芬地城地下1樓"      
#define	GET_OFFICIAL_MAP_NAME24	"愛芬"                 
#define	GET_OFFICIAL_MAP_NAME25	"地城地下2樓"          
#define	GET_OFFICIAL_MAP_NAME26	"地城地下3樓"          
#define	GET_OFFICIAL_MAP_NAME27	"血島"                 
#define	GET_OFFICIAL_MAP_NAME28	"交戰國界"             
#define	GET_OFFICIAL_MAP_NAME29	"荒岩高地"             
#define	GET_OFFICIAL_MAP_NAME30	"不朽之地"             
#define	GET_OFFICIAL_MAP_NAME31	"死寂之谷"             
#define	GET_OFFICIAL_MAP_NAME32	"沈靜森林"             
#define	GET_OFFICIAL_MAP_NAME33	"阿瑞登打鐵屋"         
#define	GET_OFFICIAL_MAP_NAME34	"愛芬打鐵屋"           
#define	GET_OFFICIAL_MAP_NAME35	"阿瑞登市政大廳"       
#define	GET_OFFICIAL_MAP_NAME36	"愛芬市政大廳"         
#define	GET_OFFICIAL_MAP_NAME37	"阿瑞登公會大廳"       
#define	GET_OFFICIAL_MAP_NAME38	"愛芬公會大廳"         
#define	GET_OFFICIAL_MAP_NAME39	"阿瑞登道具店"         
#define	GET_OFFICIAL_MAP_NAME40	"愛芬道具店"           
#define	GET_OFFICIAL_MAP_NAME41	"阿瑞登大法師之塔"     
#define	GET_OFFICIAL_MAP_NAME42	"愛芬大法師之塔"       
#define	GET_OFFICIAL_MAP_NAME43	"阿瑞登倉庫"           
#define	GET_OFFICIAL_MAP_NAME44	"愛芬倉庫"             
#define	GET_OFFICIAL_MAP_NAME45	"阿瑞登倉庫"           
#define	GET_OFFICIAL_MAP_NAME46	"愛芬倉庫"             
#define	GET_OFFICIAL_MAP_NAME47	"阿瑞森的教堂"         
#define	GET_OFFICIAL_MAP_NAME48	"愛爾迪恩的教堂"       
#define	GET_OFFICIAL_MAP_NAME49	"阿瑞登-交戰國界鄰境地"
#define	GET_OFFICIAL_MAP_NAME51	"愛芬-交戰國界鄰境地"  
#define	GET_OFFICIAL_MAP_NAME53	"地城地下4樓"          
#define	GET_OFFICIAL_MAP_NAME54	"阿瑞登的復活聖地"     
#define	GET_OFFICIAL_MAP_NAME55	"愛芬的復活聖地"       
#define	GET_OFFICIAL_MAP_NAME56	"阿瑞森花園"           
#define	GET_OFFICIAL_MAP_NAME57	"愛爾迪恩花園"         
#define	GET_OFFICIAL_MAP_NAME58	"交戰國界礦山"         
#define	GET_OFFICIAL_MAP_NAME59	"交戰國界地城"         
#define	GET_OFFICIAL_MAP_NAME60	"地獄之塔 1樓"         
#define	GET_OFFICIAL_MAP_NAME61	"地獄之塔 2樓"         
#define	GET_OFFICIAL_MAP_NAME62	"地獄之塔 3樓"         
#define GET_OFFICIAL_MAP_NAME63	"阿瑞登監獄"           
#define GET_OFFICIAL_MAP_NAME64	"愛芬監獄"   


#define	BCHECK_LOCAL_CHAT_COMMAND1	"角色%s: 由拒絕接收訊息清單中刪除."  
#define	BCHECK_LOCAL_CHAT_COMMAND2	"自己無法拒絕接收自己的訊息."        
#define	BCHECK_LOCAL_CHAT_COMMAND3	"角色%s: 已登錄在訊息拒絕接收清單中."
#define	BCHECK_LOCAL_CHAT_COMMAND4	"訊息拒絕接收清單已無多餘空間."      
#define	BCHECK_LOCAL_CHAT_COMMAND5	"欲拒絕接收訊息之角色名字太長."      
                                                                             
                                                                             
#define	BCHECK_ITEM_OPERATION_ENABLE1	"道具相關的處理尚未完成."            
                                                                             
                                                                             
#define	CLEAR_SKILL_USING_STATUS1	"技能使用已中止."                    


#define	NPC_TALK_HANDLER16	"目  標: %s %d消滅"                
#define	NPC_TALK_HANDLER17	"位置: 無關"                       
#define	NPC_TALK_HANDLER18	"地圖: %s"                         
#define	NPC_TALK_HANDLER19	"座 標: %d,%d 範圍: %d 範圍以內"   
#define	NPC_TALK_HANDLER20	"貢獻度: %d點"                     
#define	NPC_TALK_HANDLER21	"目  標: 滲透敵軍後觀察敵軍行動"   
#define	NPC_TALK_HANDLER22	"位置: 無關"                       
#define	NPC_TALK_HANDLER23	"地圖: %s"                         
#define	NPC_TALK_HANDLER24	"座 標: %d,%d 範圍: %d範圍以內"    
#define	NPC_TALK_HANDLER25	"貢獻度: %d點"                     
#define	NPC_TALK_HANDLER26	"作戰內容: 入侵敵軍後方."          
#define	NPC_TALK_HANDLER27	"直接傳送至敵軍後方地區"           
#define	NPC_TALK_HANDLER28	"破壞主要設施,或是"                
#define	NPC_TALK_HANDLER29	"使用游擊戰術"                     
#define	NPC_TALK_HANDLER30	"干擾敵軍活動的進行."              
#define	NPC_TALK_HANDLER31	"直接傳送目的地: 不可預知"         
#define	NPC_TALK_HANDLER32	"直接傳送目的地: %s"               
#define	NPC_TALK_HANDLER33	"如果你能成功, 我將非常地感激你."
#define	NPC_TALK_HANDLER34	"怎樣, 想要試試看嗎?"
#define	NPC_TALK_HANDLER35	"你要接受此任務嗎?"


#define	NPC_NAME_MERCENARY	"傭兵"
#define BGET_NPC_NAME23	", 隊員"

#define	GET_ITEM_NAME1	"純度:%d%% "             
#define	GET_ITEM_NAME2	"完成度:%d%% "           
#define	GET_ITEM_NAME3	"必殺的"                 
#define	GET_ITEM_NAME4	"中毒的"                 
#define	GET_ITEM_NAME5	"正義的"                 
#define	GET_ITEM_NAME6	"敏捷的 "                
#define	GET_ITEM_NAME7	"輕便的 "                
#define	GET_ITEM_NAME8	"銳利的 "                
#define	GET_ITEM_NAME9	"強化的 "                
#define	GET_ITEM_NAME10	"古文明的 "              
#define	GET_ITEM_NAME11	"特殊能力的 "            
#define	GET_ITEM_NAME12	"法力轉換的 "            
#define	GET_ITEM_NAME13	"必殺充電的 "            
#define	GET_ITEM_NAME14	"必殺技傷害值 +%d "      
#define	GET_ITEM_NAME15	"中毒傷害值 +%d "        
#define	GET_ITEM_NAME16	"攻擊速度 -1  "          
#define	GET_ITEM_NAME17	"重量%d%%輕量化 "        
#define	GET_ITEM_NAME18	" 增加最大傷害值 "       
#define	GET_ITEM_NAME19	"耐力增加%d%% "          
#define	GET_ITEM_NAME20	"增加最大傷害值 "        
#define	GET_ITEM_NAME21	"魔法成功率+增加%d%%"    
#define	GET_ITEM_NAME22	"被攻擊時變換為%d%% 法力"
#define	GET_ITEM_NAME23	"被攻擊時必殺技變換%d%%" 
#define	GET_ITEM_NAME24	"毒性抵抗+%d%%"          
#define	GET_ITEM_NAME25	"攻擊命中+%d"            
#define	GET_ITEM_NAME26	"物理防禦+%d"            
#define	GET_ITEM_NAME27	"生命值恢復+%d%%"        
#define	GET_ITEM_NAME28	"耐力值恢復+%d%%"        
#define	GET_ITEM_NAME29	"魔力值恢復+%d%%"        
#define	GET_ITEM_NAME30	"魔法抵抗+%d%%"          
#define	GET_ITEM_NAME31	"物理吸收%d%%"           
#define	GET_ITEM_NAME32	"魔法吸收%d%%"           
#define	GET_ITEM_NAME33	"連續攻擊+%d "           
#define	GET_ITEM_NAME34	"經驗值+%d%% "           
#define	GET_ITEM_NAME35	"金幣+%d%% "             

#define	CALC_SOCKET_CLOSED1	"你的計費Socket中斷，遊戲終了."        
                                                                       
                                                                       
#define	POINT_COMMAND_HANDLER1	"未選擇欲參加隊伍的角色，無法參加隊伍."

#define	UPDATE_SCREEN_ONGAME1	"道具相關處理尚未結束無法丟棄或給予道具."                    
#define	UPDATE_SCREEN_ONGAME5	"無法將道具給自己."                                          
#define	UPDATE_SCREEN_ONGAME6	"無法同時販賣12個以上的道具."                                
#define	UPDATE_SCREEN_ONGAME7	"道具傳送的距離太遠."                                        
#define	UPDATE_SCREEN_ONGAME8	"輸入的道具數量不正確."                                      
#define	UPDATE_SCREEN_ONGAME9	"輸入的件數比擁有的道具件數多."                              
#define	UPDATE_SCREEN_ONGAME10	"剩餘耐用度: %d"                                             
#define	UPDATE_SCREEN_ONGAME12	"按下F1鍵後會出現輔助語."                                    
#define	UPDATE_SCREEN_ONGAME13	"連結結束中...%d"                                            
#define	UPDATE_SCREEN_ONGAME14	"遊戲重新開始...%d"                                          


#define	MOTION_RESPONSE_HANDLER2	"當登出遊戲倒數期間, 若生命值減少的話即會取消登出的動作."


#define	COMMAND_PROCESSOR1	"已取消."                  
#define	COMMAND_PROCESSOR2	"網路連線品質不佳，請稍候."
                                                           
                                                           
#define	DRAW_DIALOGBOX_BANK1	"道具領回處理中."          
#define	DRAW_DIALOGBOX_BANK2	"請稍候等處理結束."        
#define	DRAW_DIALOGBOX_BANK3	""
#define	DRAW_DIALOGBOX_BANK4	"保管中的道具清單."
#define	DRAW_DIALOGBOX_BANK5	"請選擇要領回的道具."      


#define	DRAW_DIALOGBOX_CHARACTER1	"犯罪者(%d)"        
#define	DRAW_DIALOGBOX_CHARACTER2	"貢獻度(%d)"        
#define	DRAW_DIALOGBOX_CHARACTER3	"阿瑞登 %s 公會會長"
#define	DRAW_DIALOGBOX_CHARACTER4	"愛芬 %s 公會會長"  
#define	DRAW_DIALOGBOX_CHARACTER5	"阿瑞登 %s公會成員" 
#define	DRAW_DIALOGBOX_CHARACTER6	"愛芬 %s公會成員"   
#define	DRAW_DIALOGBOX_CHARACTER7	"旅行家"            
#define	DRAW_DIALOGBOX_CHARACTER8	"阿瑞登的國民"      
#define	DRAW_DIALOGBOX_CHARACTER9	"愛芬的國民"        


#define	DRAW_DIALOGBOX_LEVELUP_SETTING1	"請設定等級上升時欲增加的"
#define	DRAW_DIALOGBOX_LEVELUP_SETTING2	"屬性值點數."             
#define	DRAW_DIALOGBOX_LEVELUP_SETTING3	"* 剩餘點數: %d"          
#define	DRAW_DIALOGBOX_LEVELUP_SETTING4	"力量"                    
#define	DRAW_DIALOGBOX_LEVELUP_SETTING5	"體值"                    
#define	DRAW_DIALOGBOX_LEVELUP_SETTING6	"敏捷"                    
#define	DRAW_DIALOGBOX_LEVELUP_SETTING7	"智慧"                    
#define	DRAW_DIALOGBOX_LEVELUP_SETTING8	"魔力"                    
#define	DRAW_DIALOGBOX_LEVELUP_SETTING9	"魅力"                    
#define	DRAW_DIALOGBOX_LEVELUP_SETTING10	"等級上升的同時將使用現在設定值"
#define	DRAW_DIALOGBOX_LEVELUP_SETTING11	"增加屬性值."                   
#define	DRAW_DIALOGBOX_LEVELUP_SETTING12	"點數全部設定後"                
#define	DRAW_DIALOGBOX_LEVELUP_SETTING13	"請按Ok鍵."                     
#define	DRAW_DIALOGBOX_LEVELUP_SETTING14	"並未完成現在設定."             
#define	DRAW_DIALOGBOX_LEVELUP_SETTING15	"現在屬性值設定不正確."         
#define	DRAW_DIALOGBOX_LEVELUP_SETTING16	"等級上升時超過屬性值的最大值"  
#define	DRAW_DIALOGBOX_LEVELUP_SETTING17	"無法使用現行設定,請重新設定"   


#define	DRAW_DIALOGBOX_CITYHALL_MENU1	"申請市民權."                        
#define	DRAW_DIALOGBOX_CITYHALL_MENU4	"領取獎金."                          
#define	DRAW_DIALOGBOX_CITYHALL_MENU8	"收到英雄的批肩."                    
#define	DRAW_DIALOGBOX_CITYHALL_MENU11	"任務取消."                          
#define	DRAW_DIALOGBOX_CITYHALL_MENU14	"變更國戰所擔任的角色."              
#define	DRAW_DIALOGBOX_CITYHALL_MENU17	"選擇想要的項目."                    
                                                                             
#define	DRAW_DIALOGBOX_CITYHALL_MENU18	"成為本國市民之後. "                 
#define	DRAW_DIALOGBOX_CITYHALL_MENU19	"可買賣國家中"                       
#define	DRAW_DIALOGBOX_CITYHALL_MENU20	"所生產的大部分道具"                 
#define	DRAW_DIALOGBOX_CITYHALL_MENU21	"若是擊退其他國家的異教徒"           
#define	DRAW_DIALOGBOX_CITYHALL_MENU22	"可領取獎金, 同時並賦予"             
#define	DRAW_DIALOGBOX_CITYHALL_MENU23	"組織公會或者加入公會"               
#define	DRAW_DIALOGBOX_CITYHALL_MENU24	"以進行集體行動的資格."              
#define	DRAW_DIALOGBOX_CITYHALL_MENU25	"成為這個國家的市民"                 
#define	DRAW_DIALOGBOX_CITYHALL_MENU26	"即享有市民的權利"                   
#define	DRAW_DIALOGBOX_CITYHALL_MENU27	"你願意盡所有的責任及義務嗎?"        
                                                                             
#define	DRAW_DIALOGBOX_CITYHALL_MENU28	"申請市民權中..."                    
#define	DRAW_DIALOGBOX_CITYHALL_MENU29	"恭喜! 得到市民權."                  
#define	DRAW_DIALOGBOX_CITYHALL_MENU30	"市民權申請失敗!"                    
#define	DRAW_DIALOGBOX_CITYHALL_MENU31	"等級較低或犯罪狀態"                 
#define	DRAW_DIALOGBOX_CITYHALL_MENU32	"是無法成為市民."                    
                                                                             
#define	DRAW_DIALOGBOX_CITYHALL_MENU33	"活動的獎金"                         
#define	DRAW_DIALOGBOX_CITYHALL_MENU34	"全部加起來一共%d金幣."              
#define	DRAW_DIALOGBOX_CITYHALL_MENU35	"現在要領取獎金嗎?"                  
                                                                             
#define	DRAW_DIALOGBOX_CITYHALL_MENU46	"為了國家的安全抵抗異教徒的"         
#define	DRAW_DIALOGBOX_CITYHALL_MENU47	"侵略,授予前線的勇士們"              
#define	DRAW_DIALOGBOX_CITYHALL_MENU48	"英雄的披肩."                        
#define	DRAW_DIALOGBOX_CITYHALL_MENU49	"為了領取英雄的披肩,你的"            
#define	DRAW_DIALOGBOX_CITYHALL_MENU50	"殲滅敵人次數應在300以上"            
#define	DRAW_DIALOGBOX_CITYHALL_MENU51	"領取後 殲滅敵人"                    
#define	DRAW_DIALOGBOX_CITYHALL_MENU52	"次數減少300."                       
#define	DRAW_DIALOGBOX_CITYHALL_MENU53	"要領取英雄的披肩嗎?"                
                                                                             
#define	DRAW_DIALOGBOX_CITYHALL_MENU54	"要取消現在進行的"                   
#define	DRAW_DIALOGBOX_CITYHALL_MENU55	"任務嗎?"                            
                                                                             
                                                                             
#define	DRAW_DIALOGBOX_EXCHANGE1	"我的道具"                           
#define	DRAW_DIALOGBOX_EXCHANGE2	"數量: %d個"                         
#define	DRAW_DIALOGBOX_EXCHANGE3	"耐用度: %d/%d"                      
#define	DRAW_DIALOGBOX_EXCHANGE4	"完成度: %d%%"                       
#define	DRAW_DIALOGBOX_EXCHANGE5	"%s的道具"                           
                                                                             
#define	DRAW_DIALOGBOX_EXCHANGE9	"請等候直到對方選取要交換的道具為止" 
#define	DRAW_DIALOGBOX_EXCHANGE10	"萬一要取消交換"                     
#define	DRAW_DIALOGBOX_EXCHANGE11	"請按取消鍵."                        
                                                                             
#define	DRAW_DIALOGBOX_EXCHANGE12	"要求與其他玩家交換道具"             
#define	DRAW_DIALOGBOX_EXCHANGE13	"請選擇一樣道具與上述道具進行交換"   
#define	DRAW_DIALOGBOX_EXCHANGE14	"將欲交換的道具"                     
#define	DRAW_DIALOGBOX_EXCHANGE15	"拖曳至交換欄的空格中後"             
#define	DRAW_DIALOGBOX_EXCHANGE16	"按下交換鍵進行交換或  "             
#define	DRAW_DIALOGBOX_EXCHANGE17	"按下取消鍵拒絕交換邀請"             
                                                                             
#define	DRAW_DIALOGBOX_EXCHANGE18	"道具交換之準備已全部結束."          
#define	DRAW_DIALOGBOX_EXCHANGE19	"欲依照上述內容交換道具的話"         
#define	DRAW_DIALOGBOX_EXCHANGE20	"請按下交換鍵,欲取消交換"            
#define	DRAW_DIALOGBOX_EXCHANGE21	"請按取消鍵"                         
#define	DRAW_DIALOGBOX_EXCHANGE22	"請注意一旦按下交換鍵後"             
#define	DRAW_DIALOGBOX_EXCHANGE23	"則無法取消."                        
                                                                             
#define	DRAW_DIALOGBOX_EXCHANGE29	"   "                                
#define	DRAW_DIALOGBOX_EXCHANGE33	"請等候,直到其他玩家同意交換道具為止"
#define	DRAW_DIALOGBOX_EXCHANGE34	"雙方不同意所有交換的話"             
#define	DRAW_DIALOGBOX_EXCHANGE35	"則無法進行交易."                    
                                                                             
#define	DRAW_DIALOGBOX_EXCHANGE36	"萬一對方還未同意交換的情況"         
#define	DRAW_DIALOGBOX_EXCHANGE37	"可按取消鍵取消交換"                 
#define	DRAW_DIALOGBOX_EXCHANGE38	"但是若對方已同意交換的話"           
#define	DRAW_DIALOGBOX_EXCHANGE39	"則無法取消."                        

#define	DRAW_DIALOGBOX_FISHING1	"價值: %d金幣"
#define	DRAW_DIALOGBOX_FISHING2	"釣魚準確率:" 
#define	DRAW_DIALOGBOX_FISHING3 "現在就試試﹗"
#define	DRAW_DIALOGBOX_FISHING4 "現在就試試﹗"


#define	DRAW_DIALOGBOX_GUILDMENU1	"創立新公會"
#define	DRAW_DIALOGBOX_GUILDMENU4	"解散你的公會"
#define	DRAW_DIALOGBOX_GUILDMENU7	"購買公會加入申請書"
#define	DRAW_DIALOGBOX_GUILDMENU9	"購買公會退出申請書"
#define	DRAW_DIALOGBOX_GUILDMENU11	"預約競技場"
#define	DRAW_DIALOGBOX_GUILDMENU13	"取得競技場入場卷"

#define	DRAW_DIALOGBOX_GUILDMENU17	"* 選擇想要的項目."
#define	DRAW_DIALOGBOX_GUILDMENU18	"請輸入新增的公會名稱."
#define	DRAW_DIALOGBOX_GUILDMENU19	"新公會製作處理中..."
#define	DRAW_DIALOGBOX_GUILDMENU20	"已創造新公會."
#define	DRAW_DIALOGBOX_GUILDMENU21	"你是公會會長."
#define	DRAW_DIALOGBOX_GUILDMENU22	"新公會組織失敗."
#define	DRAW_DIALOGBOX_GUILDMENU23	"已有相同名稱的公會存在或能力不足以建立公會"
#define	DRAW_DIALOGBOX_GUILDMENU24	"公會解散:"
#define	DRAW_DIALOGBOX_GUILDMENU25	"解散你的公會. "
#define	DRAW_DIALOGBOX_GUILDMENU26	"喪失公會會長的資格"
#define	DRAW_DIALOGBOX_GUILDMENU27	"公會成員自動退出."
#define	DRAW_DIALOGBOX_GUILDMENU28	"是否同意解散公會?"

#define	DRAW_DIALOGBOX_GUILDMENU29	"公會解散處理中..."
#define	DRAW_DIALOGBOX_GUILDMENU30	"公會已解散."
#define	DRAW_DIALOGBOX_GUILDMENU31	"公會解散失敗."

#define	DRAW_DIALOGBOX_GUILDMENU32	"公會申請書為5金幣"
#define	DRAW_DIALOGBOX_GUILDMENU33	"向欲加入的公會之公會會長"
#define	DRAW_DIALOGBOX_GUILDMENU34	"提出申請將依據公會會長的判斷"
#define	DRAW_DIALOGBOX_GUILDMENU35	"決定加入與否."
#define	DRAW_DIALOGBOX_GUILDMENU36	"要購買嗎?"
#define	DRAW_DIALOGBOX_GUILDMENU37	"購買公會加入申請書."

#define	DRAW_DIALOGBOX_GUILDMENU38	"公會退出申請書的價格為5金幣"
#define	DRAW_DIALOGBOX_GUILDMENU39	"向欲加入的公會之公會會長"
#define	DRAW_DIALOGBOX_GUILDMENU40	"提出申請將依據公會會長的判斷"
#define	DRAW_DIALOGBOX_GUILDMENU41	"決定退出與否."
#define	DRAW_DIALOGBOX_GUILDMENU42	"要購買嗎?"

#define	DRAW_DIALOGBOX_GUILDMENU43	"購買公會退出申請書."

#define	DRAW_DIALOGBOX_GUILDMENU44	"費用為1500金幣.點選競技場後"
#define	DRAW_DIALOGBOX_GUILDMENU45	"即可預約競技場. 發給入場券"
#define	DRAW_DIALOGBOX_GUILDMENU46	"50張, 競技場由0時開始"
#define	DRAW_DIALOGBOX_GUILDMENU47	""
#define	DRAW_DIALOGBOX_GUILDMENU48	""
#define	DRAW_DIALOGBOX_GUILDMENU49	""
#define	DRAW_DIALOGBOX_GUILDMENU50	""

#define	DRAW_DIALOGBOX_GUILDMENU51	"1號競技場"                                     
#define	DRAW_DIALOGBOX_GUILDMENU53	"2號競技場"                                     
#define	DRAW_DIALOGBOX_GUILDMENU55	"3號競技場"                                     
#define	DRAW_DIALOGBOX_GUILDMENU57	"4號競技場"                                     
#define	DRAW_DIALOGBOX_GUILDMENU59	"5號競技場"                                     
#define	DRAW_DIALOGBOX_GUILDMENU61	"6號競技場"                                     
#define	DRAW_DIALOGBOX_GUILDMENU63	"7號競技場"                                     
#define	DRAW_DIALOGBOX_GUILDMENU65	"8號競技場"                                     
                                                                                        
#define	DRAW_DIALOGBOX_GUILDMENU66	"已預約競技場."
#define	DRAW_DIALOGBOX_GUILDMENU67	"若已預約一處的競技場的話"
#define	DRAW_DIALOGBOX_GUILDMENU68	"則無法再預約其他競技場."
                                                                                        
#define	DRAW_DIALOGBOX_GUILDMENU69	"非預約競技場之時間.."
#define	DRAW_DIALOGBOX_GUILDMENU70	"請稍候再試."

#define	DRAW_DIALOGBOX_GUILDMENU71	"所選擇的競技場已預約"
#define	DRAW_DIALOGBOX_GUILDMENU72	"請使用其他競技場."

#define	DRAW_DIALOGBOX_GUILDMENU73	"沒有足夠的金幣可預約競技場"

#define	DRAW_DIALOGBOX_GUILDMENU74	"競技場預約處理中..."

#define	DRAW_DIALOGBOX_GUILDMENU75	"請輸入新增的公會名稱."

#define	DRAW_DIALOGBOX_GUILDMENU76	"此競技場今日無法使用."
#define	DRAW_DIALOGBOX_GUILDMENU77	"請使用其他競技場."
#define	DRAW_DIALOGBOX_GUILDMENU78	"單數日可使用"
#define	DRAW_DIALOGBOX_GUILDMENU79	"阿瑞登2 4 6 8 競技場"
#define	DRAW_DIALOGBOX_GUILDMENU80	"愛芬可使用1 3 5 7 競技場"
                                                                                        
#define	DRAW_DIALOGBOX_GUILDMENU81	"已預約其他競技場."


#define	DRAW_DIALOGBOX_GUILD_OPERATION1	"公會加入申請:"                                 
#define	DRAW_DIALOGBOX_GUILD_OPERATION2	"* 上述的玩家欲加入你的公會 "                   
#define	DRAW_DIALOGBOX_GUILD_OPERATION3	" 對於此要求你可以公會會長的身分"               
#define	DRAW_DIALOGBOX_GUILD_OPERATION4	" 接受或拒絕."                                  
#define	DRAW_DIALOGBOX_GUILD_OPERATION5	"是否接受對方加入的請求."                       
                                                                                        
#define	DRAW_DIALOGBOX_GUILD_OPERATION6	"公會退出申請:"                                 
#define	DRAW_DIALOGBOX_GUILD_OPERATION7	"* 上述的玩家欲退出你的公會"                    
#define	DRAW_DIALOGBOX_GUILD_OPERATION8	" 對於此要求你可以公會會長的身分"               
#define	DRAW_DIALOGBOX_GUILD_OPERATION9	" 接受或拒絕."                                  
#define	DRAW_DIALOGBOX_GUILD_OPERATION10	"是否接受對方退出的請求."               
                                                                                        
#define	DRAW_DIALOGBOX_GUILD_OPERATION11	"公會加入成功:"                         
#define	DRAW_DIALOGBOX_GUILD_OPERATION12	"* 公會的會長接受你的申請"              
#define	DRAW_DIALOGBOX_GUILD_OPERATION13	"你已成為該公會成員."                   
                                                                                        
#define	DRAW_DIALOGBOX_GUILD_OPERATION14	"公會加入失敗:"                         
#define	DRAW_DIALOGBOX_GUILD_OPERATION15	"* 公會的會長"                          
#define	DRAW_DIALOGBOX_GUILD_OPERATION16	"拒絕你的加入申請."                     
                                                                                        
#define	DRAW_DIALOGBOX_GUILD_OPERATION17	"公會退出成功:"                         
#define	DRAW_DIALOGBOX_GUILD_OPERATION18	"* 公會的會長接受你的退出申請"          
#define	DRAW_DIALOGBOX_GUILD_OPERATION19	"你已不再是該公會成員"                  
#define	DRAW_DIALOGBOX_GUILD_OPERATION20	"具有市民的身分."                       
                                                                                        
#define	DRAW_DIALOGBOX_GUILD_OPERATION21	"公會退出拒絕:"                         
#define	DRAW_DIALOGBOX_GUILD_OPERATION22	"* 公會拒絕你的"                        
#define	DRAW_DIALOGBOX_GUILD_OPERATION23	"退出申請."                             
                                                                                        
#define	DRAW_DIALOGBOX_GUILD_OPERATION24	"公會解散:"                             
#define	DRAW_DIALOGBOX_GUILD_OPERATION25	"* 你所屬的公會已解散."                 
#define	DRAW_DIALOGBOX_GUILD_OPERATION26	"你現在已不再是公會成員"                
#define	DRAW_DIALOGBOX_GUILD_OPERATION27	"僅具有市民的資格."                     


#define	DRAW_DIALOGBOX_MAGIC1	"第一級魔法"                
#define	DRAW_DIALOGBOX_MAGIC2	"第二級魔法"                
#define	DRAW_DIALOGBOX_MAGIC3	"第三級魔法"                
#define	DRAW_DIALOGBOX_MAGIC4	"第四級魔法"                
#define	DRAW_DIALOGBOX_MAGIC5	"第五級魔法"                
#define	DRAW_DIALOGBOX_MAGIC6	"第六級魔法"                
#define	DRAW_DIALOGBOX_MAGIC7	"第七級魔法"                
#define	DRAW_DIALOGBOX_MAGIC8	"第八級魔法"                
#define	DRAW_DIALOGBOX_MAGIC9	"第九級魔法"                
#define	DRAW_DIALOGBOX_MAGIC10	"第十級魔法"                
                                                            
#define	DRAW_DIALOGBOX_MAGIC11	"你尚未學任何魔法."         
#define	DRAW_DIALOGBOX_MAGIC12	"魔法可在國家內的大魔師之塔"
#define	DRAW_DIALOGBOX_MAGIC13	"學習. 為了學習魔法"        
#define	DRAW_DIALOGBOX_MAGIC14	"需要有學習魔法所需的"      
#define	DRAW_DIALOGBOX_MAGIC15	"    "                      
#define	DRAW_DIALOGBOX_MAGIC16	"施展魔法的成功率: %d%%"    


#define	DRAW_DIALOGBOX_MAGICSHOP1	"第一級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP2	"第二級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP3	"第三級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP4	"第四級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP5	"第五級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP6	"第六級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP7	"第七級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP8	"第八級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP9	"第九級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP10	"第十級魔法"                      
#define	DRAW_DIALOGBOX_MAGICSHOP11	"法術名稱"                        
#define	DRAW_DIALOGBOX_MAGICSHOP12	"最低智慧需求"                    
#define	DRAW_DIALOGBOX_MAGICSHOP13	"  價格"                          
#define	DRAW_DIALOGBOX_MAGICSHOP14	"請選擇欲學習的魔法."             
                                                                          
                                                                          
#define	DRAW_DIALOGBOX_NOTICEMSG1	"遊戲伺服器將在%d分後中斷."       
#define	DRAW_DIALOGBOX_NOTICEMSG2	"遊戲伺服器即將中斷!"             
#define	DRAW_DIALOGBOX_NOTICEMSG3	"你必須立即登出遊戲，以確保"      
#define	DRAW_DIALOGBOX_NOTICEMSG4	"你的資料安全。在伺服器開始倒數，"
#define	DRAW_DIALOGBOX_NOTICEMSG5	"請玩家立即登出以免資料遺失"      
#define	DRAW_DIALOGBOX_NOTICEMSG6	"且資料無法恢復，請注意!!!"       
#define	DRAW_DIALOGBOX_NOTICEMSG7	"遊戲伺服器開始關閉!"             
#define	DRAW_DIALOGBOX_NOTICEMSG8	"稍候將自動結束連結. 請勿將重要的"
#define	DRAW_DIALOGBOX_NOTICEMSG9	"在道具丟在地上或儲存在倉庫中或者"
#define	DRAW_DIALOGBOX_NOTICEMSG10	"給別的玩家. 遭受損害將"          
#define	DRAW_DIALOGBOX_NOTICEMSG11	"無法恢復."                       


#define	DRAW_DIALOGBOX_NPCACTION_QUERY13	"申請"               
#define	DRAW_DIALOGBOX_NPCACTION_QUERY17	"領回"               
#define	DRAW_DIALOGBOX_NPCACTION_QUERY21	"買"                 
#define	DRAW_DIALOGBOX_NPCACTION_QUERY25	"對話"               
#define DRAW_DIALOGBOX_NPCACTION_QUERY29	"%s %d個與"
#define DRAW_DIALOGBOX_NPCACTION_QUERY29_1  "%s"

#define	DRAW_DIALOGBOX_NPCACTION_QUERY30	"給"                 
#define	DRAW_DIALOGBOX_NPCACTION_QUERY34	"交換"               
#define	DRAW_DIALOGBOX_NPCACTION_QUERY39	"賣"                 
#define	DRAW_DIALOGBOX_NPCACTION_QUERY43	"修理"               
#define	DRAW_DIALOGBOX_NPCACTION_QUERY48	"保管"               

#define	DRAW_DIALOGBOX_PARTY1	"參加隊伍."                 
#define	DRAW_DIALOGBOX_PARTY4	"離開隊伍."                 
#define	DRAW_DIALOGBOX_PARTY7	"查詢隊伍人員名單."         
                                                            
#define	DRAW_DIALOGBOX_PARTY10	"你未參加隊伍"              
#define	DRAW_DIALOGBOX_PARTY11	"你可以跟其他玩家"          
#define	DRAW_DIALOGBOX_PARTY12	"一起組隊."                 
                                                            
#define	DRAW_DIALOGBOX_PARTY13	"你已參加隊伍."             
#define	DRAW_DIALOGBOX_PARTY14	"可以離開隊伍或"            
#define	DRAW_DIALOGBOX_PARTY15	"查詢隊員的姓名 ."          
                                                            
#define	DRAW_DIALOGBOX_PARTY16	"%s已同意你參加隊伍"        
#define	DRAW_DIALOGBOX_PARTY17	"的提議，若加入隊伍"        
#define	DRAW_DIALOGBOX_PARTY18	"則隊員獲得的經驗值"        
#define	DRAW_DIALOGBOX_PARTY19	"將依照等級比例"            
#define	DRAW_DIALOGBOX_PARTY20	"進行分配."                 
                                                            
#define	DRAW_DIALOGBOX_PARTY21	"你要加入隊伍嗎?"           
                                                            
#define	DRAW_DIALOGBOX_PARTY22	"請點選你要加入"            
#define	DRAW_DIALOGBOX_PARTY23	"的隊伍的角色."             
#define	DRAW_DIALOGBOX_PARTY24	"要取消參加隊伍的話，"      
#define	DRAW_DIALOGBOX_PARTY25	"請按取消鍵."               
                                                            
#define	DRAW_DIALOGBOX_PARTY26	"已詢問%s 是否參加隊伍 "    
#define	DRAW_DIALOGBOX_PARTY27	"對方回應之前"              
#define	DRAW_DIALOGBOX_PARTY28	"請稍候."                   
#define	DRAW_DIALOGBOX_PARTY29	"要取消參加隊伍的話"        
#define	DRAW_DIALOGBOX_PARTY30	"請按取消鍵."               
                                                            
#define	DRAW_DIALOGBOX_PARTY31	"這是你加入隊伍的"          
#define	DRAW_DIALOGBOX_PARTY32	"角色名稱列表."             
#define	DRAW_DIALOGBOX_PARTY33	"正處理你離開隊伍的請求."   
#define	DRAW_DIALOGBOX_PARTY34	"請稍候."                   
#define	DRAW_DIALOGBOX_PARTY35	"已離開隊伍."               
                                                            
#define	DRAW_DIALOGBOX_PARTY36	"無法離開隊伍."             
#define	DRAW_DIALOGBOX_PARTY37	"若仍無法離開隊伍"          
#define	DRAW_DIALOGBOX_PARTY38	"直接登出遊戲，"            
#define	DRAW_DIALOGBOX_PARTY39	"就能夠離開隊伍."           
                                                            
#define	DRAW_DIALOGBOX_PARTY40	"已參加隊伍."               
#define	DRAW_DIALOGBOX_PARTY41	"能夠分享隊員們得到的"      
#define	DRAW_DIALOGBOX_PARTY42	"經驗值，"                  
#define	DRAW_DIALOGBOX_PARTY43	"即使未設定為安全模式"      
#define	DRAW_DIALOGBOX_PARTY44	"因為無法攻擊同隊伙伴"      
#define	DRAW_DIALOGBOX_PARTY45	"所以能更有效率地進行戰鬥." 
                                                            
#define	DRAW_DIALOGBOX_PARTY46	"無法加入隊伍."             
#define	DRAW_DIALOGBOX_PARTY47	"你指定的角色"              
#define	DRAW_DIALOGBOX_PARTY48	"拒絕加入隊伍"              
#define	DRAW_DIALOGBOX_PARTY49	"或者國籍不同"              
#define	DRAW_DIALOGBOX_PARTY50	"或處於非和平模式"          
#define	DRAW_DIALOGBOX_PARTY51	"以致無法共同組隊."         
                                                            
#define	DRAW_DIALOGBOX_PARTY52	"你的隊伍已經解散."         
#define	DRAW_DIALOGBOX_PARTY53	"若留在隊伍的人數只剩下一名"
#define	DRAW_DIALOGBOX_PARTY54	"隊伍會自動解散."

#define	DRAW_DIALOGBOX_PARTY55	"要離開隊伍嗎?"             
//////////////////////////////

#define	DRAW_DIALOGBOX_QUERY_DROP_ITEM_AMOUNT1	"%s: 丟棄."    
#define	DRAW_DIALOGBOX_QUERY_DROP_ITEM_AMOUNT2	"%s: 傳送給%s."
#define	DRAW_DIALOGBOX_QUERY_DROP_ITEM_AMOUNT3	"決定數量."    

#define	DRAW_DIALOGBOX_QUEST1	" 沒有進行中的任務."            
#define	DRAW_DIALOGBOX_QUEST2	"消滅怪獸任務實行中."           
#define	DRAW_DIALOGBOX_QUEST3	"消滅怪獸任務完成."             
#define	DRAW_DIALOGBOX_QUEST5	"委託人: %s"                    
                                                                
#define	DRAW_DIALOGBOX_QUEST26	"滲透敵軍任務進行中."           
#define	DRAW_DIALOGBOX_QUEST27	"滲透敵軍任務完成."             
#define	DRAW_DIALOGBOX_QUEST29	"委託人: %s"                    
#define	DRAW_DIALOGBOX_QUEST30	"目標:滲透敵軍後觀察敵軍的行動" 
#define	DRAW_DIALOGBOX_QUEST31	"位置: 無關"                    
#define	DRAW_DIALOGBOX_QUEST32	"位置: %s"                      
#define	DRAW_DIALOGBOX_QUEST33	"座 標: %d,%d 範圍: %d 區域以內"
#define	DRAW_DIALOGBOX_QUEST34	"貢獻度: %d點"                  
#define	DRAW_DIALOGBOX_QUEST35	"你的任務已取消."               


#define	DRAW_DIALOGBOX_SELL_LIST1	"%s %d個"
#define	DRAW_DIALOGBOX_SELL_LIST2	"請將要賣的道具拖曳至"      
#define	DRAW_DIALOGBOX_SELL_LIST3	"視窗內. 最多可同時販賣12件"
#define	DRAW_DIALOGBOX_SELL_LIST4	"武器或防禦具的情況"        
#define	DRAW_DIALOGBOX_SELL_LIST5	"使用耐用度若為0則無法販賣."
#define	DRAW_DIALOGBOX_SELL_LIST6	"欲將選取的道具"            
#define	DRAW_DIALOGBOX_SELL_LIST7	"由清單刪除的話"            
#define	DRAW_DIALOGBOX_SELL_LIST8	"     "                     
#define	DRAW_DIALOGBOX_SELL_LIST9	"* 將要賣的道具放在此處! *" 

#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM1	"%s %d個"
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM2	"耐用度: %d"             
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM3	"價值: %d金幣"           
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM4	"要賣這個價錢嗎?"        
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM6	"修理費用: %d金幣"       
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM7	"要修理道具嗎?"          
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM8	"正在販賣道具..."        
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM9	"在此過程結束前道具"     
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM10	"無法丟棄或給予其他道具."
#define	DRAW_DIALOGBOX_SELLOR_REPAIR_ITEM11	"道具修理中..."          


#define	DRAW_DIALOGBOX_SHOP1	"道具"                                                         
#define	DRAW_DIALOGBOX_SHOP3	"價格"                                                         
#define	DRAW_DIALOGBOX_SHOP6	"重量"                                                         
#define	DRAW_DIALOGBOX_SHOP7	": %d 金幣"                                                    
#define	DRAW_DIALOGBOX_SHOP8	": %d 重"                                                      
#define	DRAW_DIALOGBOX_SHOP9	"傷害力"                                                       
#define	DRAW_DIALOGBOX_SHOP10	"速度(最低~最高力量)"
#define	DRAW_DIALOGBOX_SHOP11	"(注意!) 力量是 %d時才可使用."
#define	DRAW_DIALOGBOX_SHOP12	"防禦值."                                                      
#define	DRAW_DIALOGBOX_SHOP15	"力量 %d 以上才能裝備"                                         
#define	DRAW_DIALOGBOX_SHOP16	"敏捷 %d 以上才能裝備"                                         
#define	DRAW_DIALOGBOX_SHOP17	"體質 %d 以上才能裝備"                                         
#define	DRAW_DIALOGBOX_SHOP18	"智慧 %d 以上才能裝備"                                         
#define	DRAW_DIALOGBOX_SHOP19	"魔力 %d 以上才能裝備"                                         
#define	DRAW_DIALOGBOX_SHOP20	"魅力 %d 以上才能裝備"                                         
#define	DRAW_DIALOGBOX_SHOP21	"(注意!) 屬性值太低無法使用.."                                 
#define	DRAW_DIALOGBOX_SHOP22	"(注意!) 男性專用."                                            
#define	DRAW_DIALOGBOX_SHOP23	"(注意!) 女性專用."                                            
#define	DRAW_DIALOGBOX_SHOP24	"等級限制"                                                     
#define	DRAW_DIALOGBOX_SHOP25	": %d以上"                                                     
#define	DRAW_DIALOGBOX_SHOP26	"(注意!) 等級過低無法使用."                                    
#define	DRAW_DIALOGBOX_SHOP27	"數量:"                                                        


#define	DRAW_DIALOGBOX_SKILLDLG2	" 現在的技能水準能製作的道具"
#define	DRAW_DIALOGBOX_SKILLDLG3	"製造道具所需的材料"         
#define	DRAW_DIALOGBOX_SKILLDLG4	"可製作的道具"               
#define	DRAW_DIALOGBOX_SKILLDLG5	"以藍色標示 "                
#define	DRAW_DIALOGBOX_SKILLDLG6	"選擇欲製作的道具."          
                                                                     
#define	DRAW_DIALOGBOX_SKILLDLG7	"技能水準: %d/%d"            
#define	DRAW_DIALOGBOX_SKILLDLG8	"製作所需的材料:"            
                                                                     
#define	DRAW_DIALOGBOX_SKILLDLG15	"欲製作上述道具請選擇材料"   
#define	DRAW_DIALOGBOX_SKILLDLG16	"放置於空格後按下"           
#define	DRAW_DIALOGBOX_SKILLDLG17	"製作按鍵."                  
                                                                     
#define	DRAW_DIALOGBOX_SKILLDLG18	" 道具製作所需的材料"        
#define	DRAW_DIALOGBOX_SKILLDLG19	"不足. "                     
#define	DRAW_DIALOGBOX_SKILLDLG20	"不足的道具以灰色標示."      
                                                                     
#define	DRAW_DIALOGBOX_SKILLDLG29	"道具製作中."                
#define	DRAW_DIALOGBOX_SKILLDLG30	"請耐心等候直到完成..."      
#define	DRAW_DIALOGBOX_SKILLDLG31	"道具製作成功!"              
                                                                     
#define	DRAW_DIALOGBOX_SKILLDLG32	"製造道具的純度為 %d%%."     
#define	DRAW_DIALOGBOX_SKILLDLG33	"製造道具的完成度為 %d%%."   
#define	DRAW_DIALOGBOX_SKILLDLG34	"道具製作失敗!"              

#define	DRAW_DIALOGBOX_SYSMENU_DETAILLEVEL   "光影效果設定"  
#define	DRAW_DIALOGBOX_SYSMENU_LOW           "低"            
#define	DRAW_DIALOGBOX_SYSMENU_NORMAL        "正常"          
#define	DRAW_DIALOGBOX_SYSMENU_HIGH          "高"            
#define	DRAW_DIALOGBOX_SYSMENU_SOUND         "聲音"          
#define	DRAW_DIALOGBOX_SYSMENU_ON            "開"            
#define	DRAW_DIALOGBOX_SYSMENU_OFF           "關"            
#define	DRAW_DIALOGBOX_SYSMENU_DISABLED      "關閉"          
#define	DRAW_DIALOGBOX_SYSMENU_MUSIC         "音樂 "         
#define	DRAW_DIALOGBOX_SYSMENU_MUSICVOLUME   "音樂音量"      
#define	DRAW_DIALOGBOX_SYSMENU_SOUNDVOLUME   "音效音量"      
#define	DRAW_DIALOGBOX_SYSMENU_TRANSPARENCY  "對話方塊隱形度"
#define DRAW_DIALOGBOX_SYSMENU_GUIDEMAP      "地圖"
#define DRAW_DIALOGBOX_SYSMENU_WHISPER       "Whisper"
#define DRAW_DIALOGBOX_SYSMENU_SHOUT         "Shout"


#define	BITEMDROP_CHARACTER1	"損壞的道具. 請將道具修理後再使用."
#define	BITEMDROP_CHARACTER2	"太重無法裝備."                    
#define	BITEMDROP_CHARACTER3	"無法裝備的道具."                  
#define	BITEMDROP_CHARACTER4	"等級太低無法裝備或使用."          
#define	BITEMDROP_CHARACTER5	"技能使用中無法裝備道具."          
#define	BITEMDROP_CHARACTER6	"男性無法使用的道具."              
#define	BITEMDROP_CHARACTER7	"女性無法使用的道具."              
#define	ITEM_EQUIPMENT_RELEASED	"道具 %s: 已解除裝備."             
#define	BITEMDROP_CHARACTER9	"道具 %s: 已裝備."                 


#define	BITEMDROP_INVENTORY1	"技能使用中無法御下裝備."      
                                                               
                                                               
#define	BITEMDROP_SELLLIST1	"要販賣的道具已登錄在清單中."  
#define	BITEMDROP_SELLLIST2	"金幣不能販賣."                
#define	BITEMDROP_SELLLIST3	"無法同時販賣12樣以上的道具."  
                                                               
                                                               
#define	BITEMDROP_SKILLDIALOG1	"道具相關的處理尚未結束."      
#define	BITEMDROP_SKILLDIALOG4	"沒有放置材料的空間."          
                                                               
                                                               
#define	DLGBOX_CLICK_BANK1	"可攜帶的道具件數已滿無法領回."
                                                               
                                                               
#define	DLGBOX_CLICK_FISH1	"魚上鉤了!試著將它拉起來."     
                                                               
                                                               
#define	DLGBOX_CLICK_MAGIC1	"為了施用魔法應空出雙手."      
#define	DLGBOX_CLICK_MAGIC2	"技能使用中無法施用魔法."      


#define	TALKING_TO_GUILDHALL_OFFICER	"正在和公會大廳管理員說話..."          
#define	TALKING_TO_SHOP_KEEPER		          "正在跟道具店老闆說話..."    
#define	TALKING_TO_BLACKSMITH_KEEPER	"正在跟打鐵屋老闆說話..."              
#define	TALKING_TO_CITYHALL_OFFICER	          "正在跟市政大廳管理員說話..."
#define	TALKING_TO_WAREHOUSE_KEEPER	          "正在跟倉庫主人說話..."      
#define	TALKING_TO_MAGICIAN		                  "正在跟魔法師說話..."
#define	DLGBOX_CLICK_NPCACTION_QUERY7	"距離太遠無法傳送道具."                
#define	DLGBOX_CLICK_NPCACTION_QUERY8	"距離太遠無法交換道具."                
#define	DLGBOX_CLICK_NPCACTION_QUERY9	"倉庫空間已滿, 無法存入."              
#define	TALKING_TO_GUARD		          "正在跟守衛說話..."          
#define	TALKING_TO_UNICORN		         "正在跟獨角獸說話..."         


#define	DLGBOX_CLICK_SHOP1	"可攜帶的道具件數已滿無法購買."
                                                               
                                                               
#define	DLGBOX_CLICK_SKILL1	"正在使用其他技能."            
#define	DLGBOX_CLICK_SKILL2	"移動中無法使用技能."          
                                                               
                                                               
#define	DLGBOX_CLICK_SKILLDLG1	"藥劑製作中..."                


#define	NOTIFYMSG_CANCEL_EXCHANGEITEM1	"已取消道具交換!"                       
#define	NOTIFYMSG_CANCEL_EXCHANGEITEM2	"對方取消交換或者並非可交換的情況."     
                                                                                
                                                                                
#define	NOTIFYMSG_CANNOT_GIVE_ITEM1	"道具 %s %d個 : 掉到地上. 無法傳送給%s."
#define	NOTIFYMSG_CANNOT_GIVE_ITEM2	"道具 %s : 掉到地上. 無法傳送給%s."     


#define	NOTIFYMSG_CANNOT_JOIN_MOREGUILDMAN1	"無法接受%s的公會加入申請要求."
#define	NOTIFYMSG_CANNOT_JOIN_MOREGUILDMAN2	"公會成員名額已滿."            


#define	NOTIFYMSG_DISMISS_GUILDMAN1	"%s退出你的公會."                            
                                                                                     
                                                                                     
#define	NOTIFYMSG_CANNOT_RATING1	"你必須友善的市民才能對其他角色使用評價命令."
#define	NOTIFYMSG_CANNOT_RATING2	"在%d秒後才可對其他角色使用評價命令."        
                                                                                     
                                                                                     
#define	NOTIFYMSG_CANNOT_REPAIR_ITEM1	"道具 %s: 不需要修理的道具."                 
#define	NOTIFYMSG_CANNOT_REPAIR_ITEM2	"道具 %s: 並非可在此處修理的道具."           
                                                                                     
	                                                                             
#define	NOTIFYMSG_CANNOT_SELL_ITEM1	"道具 %s: 無法在此處購買的道具."             
#define	NOTIFYMSG_CANNOT_SELL_ITEM2	"道具 %s: 損壞的道具不能販賣."               
#define	NOTIFYMSG_CANNOT_SELL_ITEM3	"道具 %s: 不能販賣."                         
#define	NOTIFYMSG_CANNOT_SELL_ITEM4	"為了販賣道具應取得市民權."                  
                                                                                     
#define	NOTIFYMSG_CANNOT_SELL_ITEM5	"受限於物品重量的限制，無法售出物品 ."       
#define	NOTIFYMSG_CANNOT_SELL_ITEM6	"減少物品重量後，請再嘗試."                  
                                                                                          
                                                                                          
#define	NOTIFYMSG_CHARISMA_UP	"魅力增加%d點數."       
#define	NOTIFYMSG_CHARISMA_DOWN	"魅力減少%d點數."       
                                                        
                                                        
#define	NOTIFYMSG_THROW_ITEM1	"道具 %s %d個 : 已棄置."
#define	NOTIFYMSG_THROW_ITEM2	"道具 %s : 已棄置."     
#define	NOTIFYMSG_DROPITEMFIN_ERASEITEM3	"物品 %s: 掉到地上."     
#define	NOTIFYMSG_DROPITEMFIN_ERASEITEM4	"物品 %s %d個: 掉到地上."



#define	NOTIFYMSG_ENEMYKILL_REWARD1	"與%s的戰鬥勝利!"                    
#define	NOTIFYMSG_ENEMYKILL_REWARD2	"與敵方公會%s的公會成員%s的戰鬥勝利!"
#define	EXP_DECREASED	"經驗值減少%d點."
#define	EXP_INCREASED	"經驗值增加%d點."
#define	NOTIFYMSG_ENEMYKILL_REWARD5	"殺敵數減少%d點."
#define	NOTIFYMSG_ENEMYKILL_REWARD6	"殺敵數增加%d點."
                                                         
#define	NOTIFYMSG_EVENTFISHMODE1	"開始釣魚..."    

#define	NOTIFYMSG_EXCHANGEITEM_COMPLETE1	"道具已交換!"

#define	NOTIFYMSG_FORCE_DISCONN1	"要求強制中斷連結. 無法取消連結中斷."


#define	NOTIFYMSG_GIVEITEMFIN_COUNTCHANGED1	"物品 %s %d個:  交給了 %s."            
                                                                                       
#define	NOTIFYMSG_GIVEITEMFIN_ERASEITEM2	"道具 %s %d個: 掉到地上. 無法傳送道具."
#define	NOTIFYMSG_GIVEITEMFIN_ERASEITEM3	"道具 %s %d個: 託付給倉庫主人."        
#define	NOTIFYMSG_GIVEITEMFIN_ERASEITEM4	"道具 %s %d個: 傳給公會大廳管理員."    
#define	NOTIFYMSG_GIVEITEMFIN_ERASEITEM5	"道具 %s %d個: 傳給市政大廳管理員."    
#define	NOTIFYMSG_GIVEITEMFIN_ERASEITEM6	"道具 %s %d個: 傳給魔法師."            
#define	NOTIFYMSG_GIVEITEMFIN_ERASEITEM7	"道具 %s %d個: 傳給打鐵屋老闆."        
#define	NOTIFYMSG_GIVEITEMFIN_ERASEITEM8	"道具 %s %d個: 傳給%s."                


#define	NOTIFYMSG_GLOBAL_ATTACK_MODE1	"已設定全體攻擊禁止模式!"            
#define	NOTIFYMSG_GLOBAL_ATTACK_MODE2	"現在地圖中所有物理攻擊和魔法無效化."
#define	NOTIFYMSG_GLOBAL_ATTACK_MODE3	"已解除全體攻擊禁止模式!"            


#define	NOTIFYMSG_HUNGER1	"感到飢餓..."      
#define	NOTIFYMSG_HUNGER2	"肚子餓..."        
#define	NOTIFYMSG_HUNGER3	"肚子很餓..."      
#define	NOTIFYMSG_HUNGER4	"肚子非常非常餓..."
#define	NOTIFYMSG_HUNGER5	"快要餓死了!!!!"   


#define	NOTIFYMSG_ITEMCOLOR_CHANGE1	"道具 %s: 已染色."          
#define	NOTIFYMSG_ITEMCOLOR_CHANGE2	"道具 %s: 並非可染色的道具."


#define	NOTIFYMSG_ITEMDEPlETED_ERASEITEM2	"道具 %s: 全部耗盡."
#define	NOTIFYMSG_ITEMDEPlETED_ERASEITEM3	"道具 %s: 已使用."  
#define	NOTIFYMSG_ITEMDEPlETED_ERASEITEM4	"道具 %s: 吃掉了."  
#define	NOTIFYMSG_ITEMDEPlETED_ERASEITEM6	"道具 %s: 碎掉了."  



#define	NOTIFYMSG_ITEMLIFE_SPANEND1	"道具(%s): 壞掉了!"
	


#define	NOTIFYMSG_ITEMOBTAINED1	"得到%s%d個 ."
#define	NOTIFYMSG_ITEMOBTAINED2	"得到%s ."    


#define	NOTIFYMSG_ITEMPURCHASED	"購買%s 花了%d個 金幣."

#define	NOTIFYMSG_ITEMREPAIRED1	"道具 %s: 已修理."                     
	                                                               
                                                                       
#define	NOTIFYMSG_ITEMTOBANK2	"道具 %s %d個 : 已安全保管."           
#define	NOTIFYMSG_ITEMTOBANK3	"道具 %s : 已安全保管."                
                                                                       
                                                                       
#define	NOTIFYMSG_KILLED1	"你已經死亡!"                          
#define	NOTIFYMSG_KILLED2	"你遭受%s的攻擊並且死亡!"              
#define	NOTIFYMSG_KILLED3	" 按下系統選單的重新開始鍵重新開始或者"
#define	NOTIFYMSG_KILLED4	" 按下登出鍵結束連結."                 


#define	NOTIFYMSG_LEVELUP1	"等級上升!! %d等級"


#define	NOTIFYMSG_LIMITED_LEVEL1	" 測試版使用者無法再得到經驗值!" 
                                                                         
                                                                         
#define	NOTIFYMSG_MAGICEFFECT_OFF1	"弓箭攻擊的保護效果消失."        
#define	NOTIFYMSG_MAGICEFFECT_OFF2	"魔法攻擊的保護效果消失."        
#define	NOTIFYMSG_MAGICEFFECT_OFF3	"近身戰鬥時的防禦力增加效果消失."
#define	NOTIFYMSG_MAGICEFFECT_OFF4	"不能移動魔法效果消失."          
#define	NOTIFYMSG_MAGICEFFECT_OFF5	"麻痺狀態魔法效果消失."          
#define	NOTIFYMSG_MAGICEFFECT_OFF6	"隱形魔法效果消失."              
#define	NOTIFYMSG_MAGICEFFECT_OFF7	"語言錯亂魔法效果消失."          
#define	NOTIFYMSG_MAGICEFFECT_OFF8	"混亂魔法效果消失."              
#define	NOTIFYMSG_MAGICEFFECT_OFF9	"幻覺魔法效果消失."              
#define	NOTIFYMSG_MAGICEFFECT_OFF10	"治療中毒狀態!"                  
#define	NOTIFYMSG_MAGICEFFECT_OFF11	"已解除狂暴狀態."                
#define	NOTIFYMSG_MAGICEFFECT_OFF12	"變身魔法效果消失."              
#define	NOTIFYMSG_MAGICEFFECT_OFF13	"已解除凍結狀態."                
#define	NOTIFYMSG_MAGICEFFECT_OFF14 "絕對魔法防禦效果已經消失."


#define	NOTIFYMSG_MAGICEFFECT_ON1	"產生弓箭攻擊的保護效果!"                     
#define	NOTIFYMSG_MAGICEFFECT_ON2	"被施予魔法呈現不能移動的狀態!"               
#define	NOTIFYMSG_MAGICEFFECT_ON3	"增加近身戰鬥的防禦力!"                       
#define	NOTIFYMSG_MAGICEFFECT_ON4	"被施予魔法出現不能移動狀態!"                 
#define	NOTIFYMSG_MAGICEFFECT_ON5	"被施予魔法出現麻痺狀態!"                     
#define	NOTIFYMSG_MAGICEFFECT_ON6	"因隱形魔法效果呈現別人看不到的狀態!"         
#define	NOTIFYMSG_MAGICEFFECT_ON7	"因語言混亂魔法使得你說的話別人聽不懂!"       
#define	NOTIFYMSG_MAGICEFFECT_ON8	"因混亂魔法導致無法分辨敵人及我軍!"           
#define	NOTIFYMSG_MAGICEFFECT_ON9	"中了幻覺魔法!"                               
#define	NOTIFYMSG_MAGICEFFECT_ON10	"你中毒了!"                                   
#define	NOTIFYMSG_MAGICEFFECT_ON11	"因魔法效果線為狂暴狀態! 40秒內攻擊力增加2倍."
#define	NOTIFYMSG_MAGICEFFECT_ON12	"因變身魔法效果變身為怪物!"                   
#define	NOTIFYMSG_MAGICEFFECT_ON13	"中了冰系魔法! 動作減緩50%."                  
#define	NOTIFYMSG_MAGICEFFECT_ON14  "絕對魔法防禦效果生效!"                       
                                                                                      
                                                                                      
#define	NOTIFYMSG_MAGICSTUDY_FAIL1	"魔法(%s): 學習失敗! 金幣或智慧不足."        
#define	NOTIFYMSG_MAGICSTUDY_FAIL2	"魔法(%s): 學習失敗!"                        
#define	NOTIFYMSG_MAGICSTUDY_FAIL3	" 智慧要在%d以上才能學習."                   
	


#define	NOTIFYMSG_MAGICSTUDY_SUCCESS1	"魔法(%s):已學習!"

#define	NOTIFYMSG_HP_UP	    "生命值增加%d點."    
#define	NOTIFYMSG_HP_DOWN	"生命值減少%d點."    
#define	NOTIFYMSG_MP_UP	    "魔力值增加%d點."    
#define	NOTIFYMSG_MP_DOWN	"魔力值減少%d點."    
#define	NOTIFYMSG_SP_UP	    "耐力值增加%d點."    
#define	NOTIFYMSG_SP_DOWN	"耐力值減少%d點."    
#define	NOTIFYMSG_HP2	    "登出倒數的過程中, 生命值減少的話則會取消登出遊戲."
#define	NOTIFYMSG_HP3	    "警告! 生命值太低會有危險."                        


#define	NOTIFYMSG_NEW_GUILDMAN1	"%s加入你的公會."                        
                                                                         
                                                                         
#define	NOTIFYMSG_PK_CAPTURED1	"和%d等級的玩家 %s(%d)戰鬥勝利!"         
#define	NOTIFYMSG_PK_CAPTURED3	"可以領取獎金%d金幣."                    
                                                                         
                                                                         
#define	NOTIFYMSG_PK_PENALTY1	"殺傷無辜的玩家接受處罰. 殺人數(%d)"     
#define	NOTIFYMSG_PK_PENALTY2	"經驗值減少%d點!"                        
                                                                         
#define	NOTIFYMSG_PLAYER_SHUTUP1	"%d分無法進行交談的處罰!"        
#define	NOTIFYMSG_PLAYER_SHUTUP2	"使玩家(%s)在%d分內無法進行交談."
                                                                         
                                                                         
#define	NOTIFYMSG_PLAYER_STATUS1	"%s現在遊戲伺服器中."            
#define	NOTIFYMSG_PLAYER_STATUS2	"%s現在遊戲伺服器中. %s(%d)(%d)" 
#define	NOTIFYMSG_PLAYER_STATUS3	"%s並未在此區域之內"             
                                                                                 
                                                                                 
#define	NOTIFYMSG_QUEST_REWARD1	"褒賞: 經驗值 %d點"                              
#define	NOTIFYMSG_QUEST_REWARD2	"褒賞: %s %d個"                    
#define	NOTIFYMSG_QUEST_REWARD3	"貢獻度上升%d點."                  
#define	NOTIFYMSG_QUEST_REWARD4	"貢獻度下降%d點."                  
                                                                   
                                                                   
#define	NOTIFYMSG_RATING_PLAYER1	"收到別的玩家給予好的評價."
#define	NOTIFYMSG_RATING_PLAYER2	"給予角色(%s)好的評價."    
#define	NOTIFYMSG_RATING_PLAYER3	"給予角色(%s)壞的評價."    

#define	NOTIFYMSG_SHOW_MAP1	"沒有符合現在位置的地圖."
                                                         
                                                         
#define	NOTIFYMSG_SKILL1	"技能%s: 增加%d%% ."     
#define	NOTIFYMSG_SKILL2	"技能%s: 減少%d%% ."     


#define	NOTIFYMSG_SKILL_TRAIN_SUCCESS1	"技能(%s): 學到新技能! 技術水準為%d%%."
                                                                               
                                                                               
#define	NOTIFYMSG_SKILL_USINGEND1	"技能使用失敗!"                        
#define	NOTIFYMSG_SKILL_USINGEND2	"技能使用成功!"                        




#define	NOTIFYMSG_TOTAL_USER1	"現在總使用者人數為%d名"
                                                        
                                                        
#define	NOTIFYMSG_WHISPERMODE1	"設定你與%s的密語狀態." 
#define	NOTIFYMSG_WHISPERMODE2	"解除密語狀態."         


#define	DRAWDIALOGBOX_CRUSADEJOB1	"決定國戰時你所擔任的"        
#define	DRAWDIALOGBOX_CRUSADEJOB2	"角色. 在現在的狀態下"        
#define	DRAWDIALOGBOX_CRUSADEJOB3	"可擔任的角色如下."           
#define	DRAWDIALOGBOX_CRUSADEJOB4	"請點選欲擔任的角色."         
                                                                      
#define	DRAWDIALOGBOX_CRUSADEJOB5	"指揮官"                      
#define	DRAWDIALOGBOX_CRUSADEJOB7	"軍人 "                       
#define	DRAWDIALOGBOX_CRUSADEJOB9	"建築師 "                     
#define	DRAWDIALOGBOX_CRUSADEJOB10	"想進一步了解各個角色的話"    
#define	DRAWDIALOGBOX_CRUSADEJOB17	"請點選以下的輔助鍵."         
#define	DRAWDIALOGBOX_CRUSADEJOB18	"國戰期間你所擔任的角色為"    
#define	DRAWDIALOGBOX_CRUSADEJOB19	"是軍人 ."                    
#define	DRAWDIALOGBOX_CRUSADEJOB20	"是建築師 ."                  
#define	DRAWDIALOGBOX_CRUSADEJOB21	"是指揮官 ."                  
#define	DRAWDIALOGBOX_CRUSADEJOB22	"想進一步了解擔任的角色的話"  
#define	DRAWDIALOGBOX_CRUSADEJOB23	"請點選這裡."                 
#define	DRAWDIALOGBOX_CRUSADEJOB25	"想擔任其他角色的話請去找位於"
#define	DRAWDIALOGBOX_CRUSADEJOB26	"市政大廳的管理員."           

#define	SHOW_EVENT_LIST1	"技能使用中..."

#define	REQUEST_TELEPORT_AND_WAIT_DATA1	"你無法進入此地城,僅限等級30~80以上的玩家."


#define	INITDATA_RESPONSE_HANDLER1	"這地方是 %s."


#define	MOTION_EVENT_HANDLER1	"轉為攻擊模式."
#define	MOTION_EVENT_HANDLER2	"轉為和平模式."


#define	DRAW_DIALOGBOX_COMMANDER1	"交戰國界戰爭建築物狀況"      
#define	DRAW_DIALOGBOX_COMMANDER2	"交戰國界傳送點設定"          
#define	DRAW_DIALOGBOX_COMMANDER3	"傳送至選擇的區域"            
#define	DRAW_DIALOGBOX_COMMANDER4	"召喚戰鬥單位"                
#define	DRAW_DIALOGBOX_COMMANDER5	"交戰國界建築物設定"          
#define	DRAW_DIALOGBOX_COMMANDER6	"指揮官命令輔助"              
#define	DRAW_DIALOGBOX_COMMANDER7	"點擊並選擇傳送點."           
#define	DRAW_DIALOGBOX_COMMANDER8	"回到指揮官主選項"            
#define	DRAW_DIALOGBOX_COMMANDER9	"傳送點設置輔助"              
#define	DRAW_DIALOGBOX_COMMANDER10	"傳送至選擇的區域"            
#define	DRAW_DIALOGBOX_COMMANDER11	"傳送確認(再點選一次)"        
#define	DRAW_DIALOGBOX_COMMANDER12	"回到指揮官主選項"            
#define	DRAW_DIALOGBOX_COMMANDER13	"傳送功能輔助"                
#define	DRAW_DIALOGBOX_COMMANDER14	"召喚戰鬥單位"                
#define	DRAW_DIALOGBOX_COMMANDER15	"目前召喚點數: %d"            
#define	DRAW_DIALOGBOX_COMMANDER16	"戰鬥泥人"                    
#define	DRAW_DIALOGBOX_COMMANDER17	"召喚點數3000"                
#define	DRAW_DIALOGBOX_COMMANDER18	"教壇之刀"                    
#define	DRAW_DIALOGBOX_COMMANDER19	"召喚點數2000"                
#define	DRAW_DIALOGBOX_COMMANDER20	"輕型戰鬥甲蟲"                
#define	DRAW_DIALOGBOX_COMMANDER21	"召喚點數1000"                
#define	DRAW_DIALOGBOX_COMMANDER22	"投石機"                      
#define	DRAW_DIALOGBOX_COMMANDER23	"召喚點數1500"                
#define	DRAW_DIALOGBOX_COMMANDER24	"保護主人模式"                
#define	DRAW_DIALOGBOX_COMMANDER25	"警戒模式"                    
#define	DRAW_DIALOGBOX_COMMANDER26	"回到指揮官主選項"            
#define	DRAW_DIALOGBOX_COMMANDER27	"戰鬥單位相關輔助"            
#define	DRAW_DIALOGBOX_COMMANDER28	"神之劍騎"                    
#define	DRAW_DIALOGBOX_COMMANDER29	"召喚點數3000"                
#define	DRAW_DIALOGBOX_COMMANDER30	"神之劍"                      
#define	DRAW_DIALOGBOX_COMMANDER31	"召喚點數2000"                
#define	DRAW_DIALOGBOX_COMMANDER32	"輕戰鬥甲蟲"                  
#define	DRAW_DIALOGBOX_COMMANDER33	"召喚點數1000"                
#define	DRAW_DIALOGBOX_COMMANDER34	"投石機"                      
#define	DRAW_DIALOGBOX_COMMANDER35	"召喚點數1500"                
#define	DRAW_DIALOGBOX_COMMANDER36	"保護主人模式"                
#define	DRAW_DIALOGBOX_COMMANDER37	"警戒模式"                    
#define	DRAW_DIALOGBOX_COMMANDER38	"回到指揮官主選項"            
#define	DRAW_DIALOGBOX_COMMANDER39	"召喚戰鬥兵員輔助說明"        
                                                                      
#define	DRAW_DIALOGBOX_COMMANDER40	"選擇想召喚的單位或指示行動"  
#define	DRAW_DIALOGBOX_COMMANDER41	"請點選圖示. 想獲得進一步內容"
#define	DRAW_DIALOGBOX_COMMANDER42	"請按輔助說明鍵."             
#define	DRAW_DIALOGBOX_COMMANDER43	"守衛模示"                    
#define	DRAW_DIALOGBOX_COMMANDER44	"停留模示"                    
#define	DRAW_DIALOGBOX_COMMANDER47	"選擇設置建築物的區域."       
#define	DRAW_DIALOGBOX_COMMANDER48	"回到指揮官主選項"            
#define	DRAW_DIALOGBOX_COMMANDER49	"設置建築物輔助說明"          

#define	DRAW_DIALOGBOX_CONSTRUCTOR1	"建築物位置: %s %d,%d"    
#define	DRAW_DIALOGBOX_CONSTRUCTOR2	"建築物無法使用: 無法建築"
#define	DRAW_DIALOGBOX_CONSTRUCTOR3	"選擇戰爭建築"            
#define	DRAW_DIALOGBOX_CONSTRUCTOR4	"指揮官設置傳送位置"      
#define	DRAW_DIALOGBOX_CONSTRUCTOR5	"建築師輔助說明"          
#define	DRAW_DIALOGBOX_CONSTRUCTOR6	"選擇戰爭建築"            
#define	DRAW_DIALOGBOX_CONSTRUCTOR7	"建造戰爭建築."           
#define	DRAW_DIALOGBOX_CONSTRUCTOR8	"點選圖示後即會產生元件"  
#define	DRAW_DIALOGBOX_CONSTRUCTOR9	"使用十字鎬攻擊元件"      
#define	DRAW_DIALOGBOX_CONSTRUCTOR10	"即會開始慢慢建造."       
#define	DRAW_DIALOGBOX_CONSTRUCTOR11	"在建築物完成之前"        
#define	DRAW_DIALOGBOX_CONSTRUCTOR12	"將不會有任何作用."       
#define	DRAW_DIALOGBOX_CONSTRUCTOR13	"魔法能量採集機"          
#define	DRAW_DIALOGBOX_CONSTRUCTOR14	"偵測儀"                  
#define	DRAW_DIALOGBOX_CONSTRUCTOR15	"箭矢守護台"              
#define	DRAW_DIALOGBOX_CONSTRUCTOR16	"巨砲守護台"              
#define	DRAW_DIALOGBOX_CONSTRUCTOR17	"回到建築選項"            
#define	DRAW_DIALOGBOX_CONSTRUCTOR18	"建築物輔助說明"          
#define	DRAW_DIALOGBOX_CONSTRUCTOR19	"傳送至指揮官指定的位置"  
#define	DRAW_DIALOGBOX_CONSTRUCTOR20	"確認傳送(再按一次)"      
#define	DRAW_DIALOGBOX_CONSTRUCTOR21	"回到建築師選單"          
#define	DRAW_DIALOGBOX_CONSTRUCTOR22	"傳送輔助說明"            

#define	DRAW_DIALOGBOX_SOLDIER1	"傳送位置: %s %d,%d"      
#define	DRAW_DIALOGBOX_SOLDIER2	"傳送位置未設定."         
#define	DRAW_DIALOGBOX_SOLDIER3	"傳送至指揮官指定的位置"  
#define	DRAW_DIALOGBOX_SOLDIER4	"軍人輔助說明"            
#define	DRAW_DIALOGBOX_SOLDIER5	"傳送至指揮官指定的位置"  
#define	DRAW_DIALOGBOX_SOLDIER6	"確認傳送(再按一次)"      
#define	DRAW_DIALOGBOX_SOLDIER7	"回到軍人選單"            
#define	DRAW_DIALOGBOX_SOLDIER8	"傳送輔助說明"            
                                                          
#define	DRAW_DIALOGBOX_HELP1	"黑布列斯世界"            
#define	DRAW_DIALOGBOX_HELP2	"公告事項"                
#define	DRAW_DIALOGBOX_HELP3	"角色移動方法"            
#define	DRAW_DIALOGBOX_HELP4	"攻擊,防禦,敵人,已方,中立"
#define	DRAW_DIALOGBOX_HELP5	"遊戲介面"                
#define	DRAW_DIALOGBOX_HELP6	"魔法"                    
#define	DRAW_DIALOGBOX_HELP7	"屬性值,技能系統"         
#define	DRAW_DIALOGBOX_HELP8	"公會組織"                
#define	DRAW_DIALOGBOX_HELP9	"道具說明"                
#define	DRAW_DIALOGBOX_HELP10	"對話系統"                
#define	DRAW_DIALOGBOX_HELP11	"國戰說明"                
#define	DRAW_DIALOGBOX_HELP12	"遊戲指令說明"            
#define	DRAW_DIALOGBOX_HELP13	"新手指南"                

#define NOTIFYMSG_CREATE_SCREENSHOT1 "現在的畫面 已存於 %s 檔案."
#define NOTIFYMSG_CREATE_SCREENSHOT2 "無法再儲存 拍攝畫面."      

#define DRAW_DIALOGBOX_ITEMUPGRADE1 "將欲升級的物品"          
#define DRAW_DIALOGBOX_ITEMUPGRADE2 "在從持有物品視窗中拿出後"
#define DRAW_DIALOGBOX_ITEMUPGRADE3 "按升級鍵即可  ."         
#define DRAW_DIALOGBOX_ITEMUPGRADE5 "正在進行物品升級."       
#define DRAW_DIALOGBOX_ITEMUPGRADE6 "請稍後..."               
#define DRAW_DIALOGBOX_ITEMUPGRADE7 "恭喜! 物品的升級"        
#define DRAW_DIALOGBOX_ITEMUPGRADE8 "已經成功!"
#define DRAW_DIALOGBOX_ITEMUPGRADE9 "物品的升級失敗."
#define DRAW_DIALOGBOX_ITEMUPGRADE11 "物品升級點數 : %d"
#define DRAW_DIALOGBOX_ITEMUPGRADE12 "需要的升級點數 : %d"
// v2.16 2002-5-20 堅惜⑷ 熱薑 
#define DRAW_DIALOGBOX_ITEMUPGRADE13 "請選擇升級種類."              
#define DRAW_DIALOGBOX_ITEMUPGRADE14 "一般物品升級"                 
#define DRAW_DIALOGBOX_ITEMUPGRADE15 "至尊物品升級"                 
#define DRAW_DIALOGBOX_ITEMUPGRADE16 "升級一般物品."                
#define DRAW_DIALOGBOX_ITEMUPGRADE17 "若要升級武器類的物品"         
#define DRAW_DIALOGBOX_ITEMUPGRADE18 "要有聖者之石, 要升級防具類"   
#define DRAW_DIALOGBOX_ITEMUPGRADE19 "物品的話"                     
#define DRAW_DIALOGBOX_ITEMUPGRADE20 "必須要有"                     
#define DRAW_DIALOGBOX_ITEMUPGRADE21 "梅林之石."                    
#define DRAW_DIALOGBOX_ITEMUPGRADE22 "升級至尊物品."                
#define DRAW_DIALOGBOX_ITEMUPGRADE23 "為了要升級至尊物品"           
#define DRAW_DIALOGBOX_ITEMUPGRADE24 "需要充分的至尊物品"           
#define DRAW_DIALOGBOX_ITEMUPGRADE25 "升級點數."                    
#define DRAW_DIALOGBOX_ITEMUPGRADE26 "* 至尊物品以此方法"           
#define DRAW_DIALOGBOX_ITEMUPGRADE27 "無法升級."                    
#define DRAW_DIALOGBOX_ITEMUPGRADE28 "* 一般物品以此方法"           
#define DRAW_DIALOGBOX_ITEMUPGRADE29 "無法升級."                    
#define DRAW_DIALOGBOX_ITEMUPGRADE30 "並無擁有聖者之石或是梅林之石."
#define DRAW_DIALOGBOX_ITEMUPGRADE31 "欲升級的一般物品"             
#define DRAW_DIALOGBOX_ITEMUPGRADE32 "從持有品欄中拿出後"           
#define DRAW_DIALOGBOX_ITEMUPGRADE33 "按升級鍵 ."                   
#define DRAW_DIALOGBOX_ITEMUPGRADE34 "武器升級可能的次數: %d"       
#define DRAW_DIALOGBOX_ITEMUPGRADE35 "防具升級可能的次數: %d"       
#define DRAW_DIALOGBOX_ITEMUPGRADE36 "物品升級失敗的話"             
#define DRAW_DIALOGBOX_ITEMUPGRADE37 "物品會消失.真可惜啊 !"        
// v2.17 2002-7-21
#define DRAW_DIALOGBOX_ITEMUPGRADE38 "該物品已無法繼續升級。"
#define DRAW_DIALOGBOX_ITEMUPGRADE39 "該物品是不可升級的物品。"
#define DRAW_DIALOGBOX_ITEMUPGRADE40 "沒有必要的物品升級點數。"

#define DRAW_DIALOGBOX_ITEMUPGRADE41 "你可以升級的只有防具."
#define DRAW_DIALOGBOX_ITEMUPGRADE42 "你可以升級的只有武器."

#define NOTIFY_MSG_HANDLER_GIZONITEMUPGRADELEFT1 "至尊物品能夠升級! 請按物品視窗的升級鍵 ."
#define DLGBOXCLICK_INVENTORY1	"要製作物品的話，要學習武器防具製造的技能 ."
#define DLGBOXCLICK_INVENTORY2	"請在打鐵屋購買並使用武器防具製作手冊. 更詳細的內容請參考說明內容."

#define NOTIFY_MSG_CONVERT_WALKING_MODE "走路模式"
#define NOTIFY_MSG_CONVERT_RUNNING_MODE "跑步模式"
#define NOTIFY_MSG_MUSIC_OFF			"音樂關閉"
#define NOTIFY_MSG_MUSIC_ON				"音樂開啟"
#define NOTIFY_MSG_SOUND_OFF			"音效關閉"
#define NOTIFY_MSG_SOUND_ON				"音效開啟"

#define NOTIFY_MSG_STRUCTURE_HP         "建築物的耐久力 :"
#define NOTIFY_MSG_CRUSADESTART_NONE    "旅行家在國戰期間無法進入國家."
                                                                                                
#define NOTIFY_MSG_DETAIL_LEVEL_LOW		"光影效果設定 : 低"                            
#define NOTIFY_MSG_DETAIL_LEVEL_MEDIUM	"光影效果設定 : 正常"                                 
#define NOTIFY_MSG_DETAIL_LEVEL_HIGH	"光影效果設定 : 高"                                   

#define	MSG_SHORTCUT1	"尚未設定道具或魔法的快速鍵."               
#define	MSG_SHORTCUT2	"若要設定快速鍵[F%d]在裝備道具或施展魔法後，"
#define	MSG_SHORTCUT3	"按下[Control]＋[F%d]鍵即可設定."            
#define	MSG_SHORTCUT4	"道具(%s %s %s): 設定了[F%d]按鍵."
#define	MSG_SHORTCUT5	"魔法(%s): 設定了[F%d]按鍵."      

#define NOTIFY_MSG_FORCERECALLTIME1 "強制召回時間約%d分鐘。在敵方的村莊中無法進行召回。"
#define NOTIFY_MSG_FORCERECALLTIME2 "即將被強制召回。"

#define DEF_MSG_TOTAL_NUMBER "%d個"
#define DEF_MSG_EXP	"經驗值: "

#define DEF_MSG_CHARACTERNAME	"角色名稱"
#define DEF_MSG_GENDER			"性別"
#define DEF_MSG_SKINCOLOR		"膚色"
#define DEF_MSG_HAIRSTYLE		"髮型"
#define DEF_MSG_HAIRCOLOR		"髮色"
#define DEF_MSG_UNDERWEARCOLOR	"內衣顏色"
#define DEF_MSG_STRENGTH		"力量"
#define DEF_MSG_VITALITY		"體質"
#define DEF_MSG_DEXTERITY		"敏捷"
#define DEF_MSG_INTELLIGENCE	"智慧"
#define DEF_MSG_MAGIC			"魔力"
#define DEF_MSG_CHARISMA		"魅力"
#define DEF_MSG_HITPOINT		"生命值"
#define DEF_MSG_MANAPOINT		"魔法值"
#define DEF_MSG_STAMINARPOINT	"耐力值"

#define DEF_MSG_GETNEXTMOVEDIR	"國民無法去危險地帶。需至市政大廳內變更模式才行"
#define DEF_MSG_GUIDEMAP_MIN	"(-) : 小地圖"
#define DEF_MSG_GUIDEMAP_MAX	"(+) : 擴大週邊地圖"
#define DEF_MSG_MAPNAME_CITYHALL	"市政大廳"
#define DEF_MSG_MAPNAME_MAGICTOWER	"大法師之塔"
#define DEF_MSG_MAPNAME_DUNGEON		"地下城"
#define DEF_MSG_MAPNAME_WAREHOUSE	"倉庫"
#define DEF_MSG_MAPNAME_BARRACK		"訓練所"
#define DEF_MSG_MAPNAME_GUILDHALL	"公會大廳"
#define DEF_MSG_MAPNAME_SHOP		"道具店"
#define DEF_MSG_MAPNAME_BLACKSMITH	"道具店"
#define DEF_MSG_MAPNAME_CATH		"教堂"

#define DEF_MSG_WARNING1	" ** 此地區是戰爭區域 **"
#define DEF_MSG_WARNING2	"此地區非本國之區域，所有的士兵"
#define DEF_MSG_WARNING3	"在此危險地帶將無法受到保護"
#define DEF_MSG_WARNING4	"若要安全的進行遊戲，請至村莊內的市政大廳"
#define DEF_MSG_WARNING5	"找管理員變更為國民模式"

#define	DEF_MSG_SAFEZONE	"此地是安全處"
#define	DEF_MSG_DANGERZONE	"此地無法受到保護，小心其他玩家的攻擊。"

#define DEF_MSG_ARECIVIL	"阿瑞登國民"
#define DEF_MSG_ARESOLDIER	"阿瑞登士兵"
#define DEF_MSG_ELVCIVIL	"愛芬國民"
#define DEF_MSG_ELVSOLDIER	"愛芬士兵"
#define DEF_MSG_PK			"犯罪者"
#define DEF_MSG_AREPK		"阿瑞登犯罪者"
#define DEF_MSG_ELVPK		"愛芬犯罪者"
#define DEF_MSG_GUILDMASTER		"%s 公會會長"
#define DEF_MSG_GUILDMASTER1	"  公會會長)"
#define DEF_MSG_GUILDSMAN		"%s 公會成員"
#define DEF_MSG_GUILDSMAN1		" 公會成員)"

#define GET_OFFICIAL_MAP_NAME65	"約定之地"
#define GET_OFFICIAL_MAP_NAME66	"Ice Map"

#define DEF_MSG_FORCEATTACK_ON	"跳出強制攻擊模式"
#define DEF_MSG_FORCEATTACK_OFF	"不跳出強制攻擊模式"

#define DRAW_DIALOGBOX_CITYHALL_MENU56	"變更遊戲模式"

#define DRAW_DIALOGBOX_CITYHALL_MENU57	"*你現在是國民模式*"
#define DRAW_DIALOGBOX_CITYHALL_MENU58	"*你現在是士兵模式*"
#define DRAW_DIALOGBOX_CITYHALL_MENU59	"(國民模式在全區皆很安全)"

#define DRAW_DIALOGBOX_CITYHALL_MENU60	"國民:"
#define DRAW_DIALOGBOX_CITYHALL_MENU61	"敵國士兵無法攻擊你"
#define DRAW_DIALOGBOX_CITYHALL_MENU62	"可安全的不受影響"
#define DRAW_DIALOGBOX_CITYHALL_MENU63	"慢慢提升等級。"

#define DRAW_DIALOGBOX_CITYHALL_MENU64	"士兵:"
#define DRAW_DIALOGBOX_CITYHALL_MENU65	"其他國家士兵想入侵"
#define DRAW_DIALOGBOX_CITYHALL_MENU66	"無法受到"
#define DRAW_DIALOGBOX_CITYHALL_MENU67	"保護的危險模式"
#define DRAW_DIALOGBOX_CITYHALL_MENU68	"要更換模式嗎?"
#define DRAW_DIALOGBOX_CITYHALL_MENU69	"移往其他地區"
#define DRAW_DIALOGBOX_CITYHALL_MENU70	"移往其他地區"
#define DRAW_DIALOGBOX_CITYHALL_MENU71	"需要黃金"
#define DRAW_DIALOGBOX_CITYHALL_MENU72	"選擇移動的地方"
#define DRAW_DIALOGBOX_CITYHALL_MENU72_1	"前往的區域中立角色無法進入"

#define DRAW_DIALOGBOX_CITYHALL_MENU73	"現在在檢視可以移動"
#define DRAW_DIALOGBOX_CITYHALL_MENU74	"的區域"
#define DRAW_DIALOGBOX_CITYHALL_MENU75	"請稍等一下"
#define DRAW_DIALOGBOX_CITYHALL_MENU76	"沒有可移動的區域"
#define DRAW_DIALOGBOX_CITYHALL_MENU77  "地圖名稱:%s 費用 : %d"

#define DEF_MSG_GAMEMODE_CHANGED		"遊戲模式變換"

#define DRAW_DIALOGBOX_ITEM_DROP1   "要丟此道具嗎?"
#define DRAW_DIALOGBOX_ITEM_DROP2   "同樣的道具了不需再詢問是否丟棄(開)"
#define DRAW_DIALOGBOX_ITEM_DROP3   "同樣的道具了不需再詢問是否丟棄(關)"

#define	BCHECK_LOCAL_CHAT_COMMAND7	"不接受聽密語的功能"
#define	BCHECK_LOCAL_CHAT_COMMAND8	"接受自由發聲功能 "
#define	BCHECK_LOCAL_CHAT_COMMAND9	"不接受自由發聲功能"

#define	BCHECK_LOCAL_CHAT_COMMAND6	"接受聽密語的功能"

#define RESPONSE_CHARGED_TELEPORT1 "等級過低無法前往"
#define RESPONSE_CHARGED_TELEPORT2 "凡人無法前往"
#define RESPONSE_CHARGED_TELEPORT3 "中立者無法前往"
#define RESPONSE_CHARGED_TELEPORT4 "犯罪者無法前往"
#define RESPONSE_CHARGED_TELEPORT5 "無法移動去相同的村莊"
#define RESPONSE_CHARGED_TELEPORT6 "金幣不足所以無法傳送"
#define RESPONSE_CHARGED_TELEPORT7 ".........................."

#define DEF_MSG_NOTIFY_AGRICULTURENOAREA		"非農耕區"
#define DEF_MSG_NOTIFY_AGRICULTURESKILLLIMIT	"無法以目前的農業技能來農耕"
#define DEF_MSG_NOTIFY_NOMOREAGRICULTURE		"無法農耕"

#define	TALKING_TO_MCGAFFIN				"正在跟村民講話..."
#define	TALKING_TO_PERRY				"正在跟村女講話..."
#define	TALKING_TO_DEVLIN				"正在跟魔法師說話..."