#ifndef SPRITEID_H
#define SPRITEID_H

/// Mouse Cursor
#define SPRID_CURSOR 0
#define INTERFACE_CURSOR_ARROW 0

/// SPRFONT
#define SPRID_SPRFONT 1
#define SPRID_SPRFONT2 2

/// LoadingScene
#define SPRID_LOADING 3
#define SPRID_LOADING_BACKGROUND 0
#define SPRID_LOADING_PROGRESSBAR 1

/// MenuScene
#define SPRID_MAINMENU 4
#define SPRID_MAINMENU_BACKGROUND 0
#define SPRID_MAINMENU_LOGIN 1
#define SPRID_MAINMENU_NEWACCOUNT 2
#define SPRID_MAINMENU_EXIT 3

/// ExitScene
#define SPRID_EXIT 5
#define SPRID_EXIT_BACKGROUND 0
#define SPRID_EXIT_MESSAGE 1

/// LoginScene
#define SPRID_LOGIN 6
#define SPRID_LOGIN_BACKGROUND 0
#define SPRID_LOGIN_FRAME 2
#define SPRID_LOGIN_BUTTON_CONNECT 3
#define SPRID_LOGIN_BUTTON_CANCEL 4

/// SelectServerScene
#define SPRID_SELECTSERVER_FRAME 1
#define SPRID_SELECTSERVER_BUTTON_ABADDON 5
#define SPRID_SELECTSERVER_BUTTON_APOCALYPSE 6

/// GameDialog
#define SPRID_GAMEDIALOG_0 7
#define SPRID_GAMEDIALOG_1 8
#define SPRID_GAMEDIALOG_2 9
#define SPRID_GAMEDIALOG_3 10
#define SPRID_GAMEDIALOG_4 11
#define SPRID_GAMEDIALOG_5 12
#define SPRID_GAMEDIALOG_6 13
#define SPRID_GAMEDIALOG_7 14
#define SPRID_GAMEDIALOG_8 15
#define SPRID_GAMEDIALOG_9 16
#define SPRID_GAMEDIALOG_10 17
#define INTERFACE_DIALOG_CHANGEPASSWD 0
#define INTERFACE_DIALOG_SPELLS 1
#define INTERFACE_DIALOG_MESSAGEBOX 2
#define INTERFACE_DIALOG_MESSAGEBOX2 3
#define INTERFACE_DIALOG_CHANGESTATS 4
#define INTERFACE_BUTTON_PLUS 5
#define INTERFACE_BUTTON_MINUS 6

/// SignupScene
#define SPRID_DIALOGTEXT_TITLES 18
#define SPRID_DIALOGTEXT_BUTTONS 19
#define INTERFACE_BUTTON_OK 0
#define INTERFACE_BUTTON_NO 2
#define INTERFACE_BUTTON_QUEST 4
#define INTERFACE_BUTTON_CONTINUE 6
#define INTERFACE_BUTTON_LOGOUT 8
#define INTERFACE_BUTTON_LEVELSET 10
#define INTERFACE_BUTTON_IAGREE 12
#define INTERFACE_BUTTON_DISAGREE 14
#define INTERFACE_BUTTON_CANCEL 16
#define INTERFACE_BUTTON_YES 18
#define INTERFACE_BUTTON_CHANGE 20
#define INTERFACE_BUTTON_CONNECT 22
#define INTERFACE_BUTTON_CREATE 24
#define INTERFACE_BUTTON_CLEAR 26
#define INTERFACE_BUTTON_RESET 28
#define INTERFACE_BUTTON_PURCHASE 30
#define INTERFACE_BUTTON_ACCEPT 32
#define INTERFACE_BUTTON_REJECT 34
#define INTERFACE_BUTTON_RESTART 36
#define INTERFACE_BUTTON_SELL 38
#define INTERFACE_BUTTON_DECLINE 40
#define INTERFACE_BUTTON_REPAIR 42
#define INTERFACE_BUTTON_PARTY 44
#define INTERFACE_BUTTON_UPGRADE 46
#define INTERFACE_BUTTON_ALCHEMY 48
#define INTERFACE_BUTTON_CHARLIST 50
#define INTERFACE_BUTTON_START 56
#define INTERFACE_BUTTON_CREATENEWCHAR 57
#define INTERFACE_BUTTON_DELCHAR 58
#define INTERFACE_BUTTON_CHANGEPASSWD 59
#define INTERFACE_BUTTON_LOGOUTBIG 60
#define INTERFACE_BUTTON_SLOTSELECTED 62
#define INTERFACE_BUTTON_MASTER 63

#endif // SPRITEID_H
