#ifndef SPRITEID_H
#define SPRITEID_H

#define SPRID_CURSOR 0
#define SPRID_CURSOR_NORMAL 0
#define SPRID_LOADING 1
#define SPRID_LOADING_BACKGROUND 0
#define SPRID_LOADING_PROGRESSBAR 1
#define SPRID_MAINMENU 2
#define SPRID_MAINMENU_BACKGROUND 0
#define SPRID_MAINMENU_LOGIN 1
#define SPRID_MAINMENU_NEWACCOUNT 2
#define SPRID_MAINMENU_EXIT 3
#define SPRID_EXIT 3
#define SPRID_EXIT_BACKGROUND 0
#define SPRID_EXIT_MESSAGE 1

#endif // SPRITEID_H
